package executor

import (
	"testing"
)

// TestIdentityAutoIncrement proves GENERATED ... AS IDENTITY columns auto-assign
// from an implicit sequence exactly like SERIAL.
func TestIdentityAutoIncrement(t *testing.T) {
	ex, done := newIdxExec(t)
	defer done()
	sess := testSession(t)

	run(t, ex, sess, "CREATE TABLE t (id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, name TEXT)")
	run(t, ex, sess, "INSERT INTO t (name) VALUES ('alice')")
	run(t, ex, sess, "INSERT INTO t (name) VALUES ('bob')")

	r := run(t, ex, sess, "SELECT id, name FROM t ORDER BY id")
	if len(r.Rows) != 2 || r.Rows[0][0].Text != "1" || r.Rows[1][0].Text != "2" {
		t.Fatalf("identity auto-increment: want ids 1,2 got %v", rowsText(r))
	}
}

// TestIdentityByDefault proves GENERATED BY DEFAULT AS IDENTITY auto-assigns when
// omitted.
func TestIdentityByDefault(t *testing.T) {
	ex, done := newIdxExec(t)
	defer done()
	sess := testSession(t)

	run(t, ex, sess, "CREATE TABLE t (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT)")
	run(t, ex, sess, "INSERT INTO t (name) VALUES ('x')")
	r := run(t, ex, sess, "SELECT id FROM t")
	if len(r.Rows) != 1 || r.Rows[0][0].Text != "1" {
		t.Fatalf("identity by default: want id 1 got %v", rowsText(r))
	}
}

// TestGeneratedStored proves GENERATED ALWAYS AS (expr) STORED computes the value
// on INSERT and recomputes on UPDATE.
func TestGeneratedStored(t *testing.T) {
	ex, done := newIdxExec(t)
	defer done()
	sess := testSession(t)

	run(t, ex, sess, "CREATE TABLE t (id INT PRIMARY KEY, price INT, qty INT, total INT GENERATED ALWAYS AS (price * qty) STORED)")
	run(t, ex, sess, "INSERT INTO t (id, price, qty) VALUES (1, 10, 3)")
	r := run(t, ex, sess, "SELECT total FROM t WHERE id = 1")
	if len(r.Rows) != 1 || r.Rows[0][0].Text != "30" {
		t.Fatalf("generated stored insert: want 30 got %v", rowsText(r))
	}
	run(t, ex, sess, "UPDATE t SET qty = 5 WHERE id = 1")
	r = run(t, ex, sess, "SELECT total FROM t WHERE id = 1")
	if r.Rows[0][0].Text != "50" {
		t.Fatalf("generated stored update recompute: want 50 got %v", rowsText(r))
	}
}

// TestAlterColumnSetDropDefault proves SET/DROP DEFAULT persist in the catalog.
func TestAlterColumnSetDropDefault(t *testing.T) {
	ex, done := newIdxExec(t)
	defer done()
	sess := testSession(t)

	run(t, ex, sess, "CREATE TABLE t (id INT PRIMARY KEY, status TEXT)")
	run(t, ex, sess, "ALTER TABLE t ALTER COLUMN status SET DEFAULT 'active'")
	run(t, ex, sess, "INSERT INTO t (id) VALUES (1)")
	r := run(t, ex, sess, "SELECT status FROM t WHERE id = 1")
	if r.Rows[0][0].Text != "active" {
		t.Fatalf("set default: want active got %v", rowsText(r))
	}
	run(t, ex, sess, "ALTER TABLE t ALTER COLUMN status DROP DEFAULT")
	run(t, ex, sess, "INSERT INTO t (id) VALUES (2)")
	r = run(t, ex, sess, "SELECT status FROM t WHERE id = 2")
	if !r.Rows[0][0].Null {
		t.Fatalf("drop default: want NULL got %v", rowsText(r))
	}
}

// TestAlterColumnNotNull proves SET/DROP NOT NULL toggle enforcement.
func TestAlterColumnNotNull(t *testing.T) {
	ex, done := newIdxExec(t)
	defer done()
	sess := testSession(t)

	run(t, ex, sess, "CREATE TABLE t (id INT PRIMARY KEY, name TEXT)")
	run(t, ex, sess, "ALTER TABLE t ALTER COLUMN name SET NOT NULL")
	if err := execErr(ex, sess, "INSERT INTO t (id, name) VALUES (1, NULL)"); err == nil {
		t.Fatalf("SET NOT NULL: expected error inserting NULL")
	}
	run(t, ex, sess, "ALTER TABLE t ALTER COLUMN name DROP NOT NULL")
	run(t, ex, sess, "INSERT INTO t (id, name) VALUES (2, NULL)")
	r := run(t, ex, sess, "SELECT id FROM t")
	if len(r.Rows) != 1 {
		t.Fatalf("DROP NOT NULL: want 1 row got %d", len(r.Rows))
	}
}

// TestAlterColumnType proves ALTER COLUMN TYPE updates the catalog OID.
func TestAlterColumnType(t *testing.T) {
	ex, done := newIdxExec(t)
	defer done()
	sess := testSession(t)

	run(t, ex, sess, "CREATE TABLE t (id INT PRIMARY KEY, v INT)")
	run(t, ex, sess, "INSERT INTO t (id, v) VALUES (1, 7)")
	run(t, ex, sess, "ALTER TABLE t ALTER COLUMN v TYPE BIGINT")
	r := run(t, ex, sess, "SELECT v FROM t WHERE id = 1")
	if r.Columns[0].TypeOID != OIDInt8 {
		t.Fatalf("alter type: want int8 OID got %d", r.Columns[0].TypeOID)
	}
	if r.Rows[0][0].Text != "7" {
		t.Fatalf("alter type: value preserved want 7 got %v", rowsText(r))
	}
}

// TestAlterAddUnique proves ADD CONSTRAINT UNIQUE builds an enforced unique index.
func TestAlterAddUnique(t *testing.T) {
	ex, done := newIdxExec(t)
	defer done()
	sess := testSession(t)

	run(t, ex, sess, "CREATE TABLE t (id INT PRIMARY KEY, email TEXT)")
	run(t, ex, sess, "INSERT INTO t (id, email) VALUES (1, 'a@x.com')")
	run(t, ex, sess, "ALTER TABLE t ADD CONSTRAINT t_email_key UNIQUE (email)")
	if err := execErr(ex, sess, "INSERT INTO t (id, email) VALUES (2, 'a@x.com')"); err == nil {
		t.Fatalf("ADD UNIQUE: expected duplicate error")
	}
	run(t, ex, sess, "INSERT INTO t (id, email) VALUES (3, 'b@x.com')")
}

// TestAlterAddForeignKey proves ADD CONSTRAINT FOREIGN KEY enforces the reference.
func TestAlterAddForeignKey(t *testing.T) {
	ex, done := newIdxExec(t)
	defer done()
	sess := testSession(t)

	run(t, ex, sess, "CREATE TABLE parent (id INT PRIMARY KEY)")
	run(t, ex, sess, "CREATE TABLE child (id INT PRIMARY KEY, pid INT)")
	run(t, ex, sess, "INSERT INTO parent (id) VALUES (1)")
	run(t, ex, sess, "ALTER TABLE child ADD CONSTRAINT fk FOREIGN KEY (pid) REFERENCES parent (id)")
	run(t, ex, sess, "INSERT INTO child (id, pid) VALUES (1, 1)")
	if err := execErr(ex, sess, "INSERT INTO child (id, pid) VALUES (2, 99)"); err == nil {
		t.Fatalf("ADD FK: expected FK violation for missing parent")
	}
}

// TestAlterAddCheck proves ADD CONSTRAINT CHECK is enforced on write.
func TestAlterAddCheck(t *testing.T) {
	ex, done := newIdxExec(t)
	defer done()
	sess := testSession(t)

	run(t, ex, sess, "CREATE TABLE t (id INT PRIMARY KEY, age INT)")
	run(t, ex, sess, "ALTER TABLE t ADD CONSTRAINT age_pos CHECK (age > 0)")
	if err := execErr(ex, sess, "INSERT INTO t (id, age) VALUES (1, -5)"); err == nil {
		t.Fatalf("ADD CHECK: expected violation for age=-5")
	}
	run(t, ex, sess, "INSERT INTO t (id, age) VALUES (2, 10)")
}

// TestRenameTable proves RENAME TO migrates data so it is accessible under the
// new name and gone from the old.
func TestRenameTable(t *testing.T) {
	ex, done := newIdxExec(t)
	defer done()
	sess := testSession(t)

	run(t, ex, sess, "CREATE TABLE old_t (id INT PRIMARY KEY, name TEXT)")
	run(t, ex, sess, "INSERT INTO old_t (id, name) VALUES (1, 'alice')")
	run(t, ex, sess, "INSERT INTO old_t (id, name) VALUES (2, 'bob')")
	run(t, ex, sess, "ALTER TABLE old_t RENAME TO new_t")

	r := run(t, ex, sess, "SELECT id, name FROM new_t ORDER BY id")
	if len(r.Rows) != 2 || r.Rows[0][1].Text != "alice" || r.Rows[1][1].Text != "bob" {
		t.Fatalf("rename: data not accessible under new name: %v", rowsText(r))
	}
	if err := execErr(ex, sess, "SELECT * FROM old_t"); err == nil {
		t.Fatalf("rename: old name should no longer resolve")
	}
}

// TestOnDeleteCascade proves ON DELETE CASCADE removes referencing children.
func TestOnDeleteCascade(t *testing.T) {
	ex, done := newIdxExec(t)
	defer done()
	sess := testSession(t)

	run(t, ex, sess, "CREATE TABLE parent (id INT PRIMARY KEY)")
	run(t, ex, sess, "CREATE TABLE child (id INT PRIMARY KEY, pid INT REFERENCES parent (id) ON DELETE CASCADE)")
	run(t, ex, sess, "INSERT INTO parent (id) VALUES (1)")
	run(t, ex, sess, "INSERT INTO child (id, pid) VALUES (10, 1)")
	run(t, ex, sess, "INSERT INTO child (id, pid) VALUES (11, 1)")
	run(t, ex, sess, "DELETE FROM parent WHERE id = 1")

	r := run(t, ex, sess, "SELECT id FROM child")
	if len(r.Rows) != 0 {
		t.Fatalf("ON DELETE CASCADE: want 0 children got %d", len(r.Rows))
	}
}

// TestOnDeleteSetNull proves ON DELETE SET NULL nulls child FK columns.
func TestOnDeleteSetNull(t *testing.T) {
	ex, done := newIdxExec(t)
	defer done()
	sess := testSession(t)

	run(t, ex, sess, "CREATE TABLE parent (id INT PRIMARY KEY)")
	run(t, ex, sess, "CREATE TABLE child (id INT PRIMARY KEY, pid INT REFERENCES parent (id) ON DELETE SET NULL)")
	run(t, ex, sess, "INSERT INTO parent (id) VALUES (1)")
	run(t, ex, sess, "INSERT INTO child (id, pid) VALUES (10, 1)")
	run(t, ex, sess, "DELETE FROM parent WHERE id = 1")

	r := run(t, ex, sess, "SELECT id, pid FROM child")
	if len(r.Rows) != 1 || !r.Rows[0][1].Null {
		t.Fatalf("ON DELETE SET NULL: want child with NULL pid got %v", rowsText(r))
	}
}

// TestOnDeleteRestrict proves the default action still blocks deletes.
func TestOnDeleteRestrict(t *testing.T) {
	ex, done := newIdxExec(t)
	defer done()
	sess := testSession(t)

	run(t, ex, sess, "CREATE TABLE parent (id INT PRIMARY KEY)")
	run(t, ex, sess, "CREATE TABLE child (id INT PRIMARY KEY, pid INT REFERENCES parent (id))")
	run(t, ex, sess, "INSERT INTO parent (id) VALUES (1)")
	run(t, ex, sess, "INSERT INTO child (id, pid) VALUES (10, 1)")
	if err := execErr(ex, sess, "DELETE FROM parent WHERE id = 1"); err == nil {
		t.Fatalf("default RESTRICT: expected delete to be blocked")
	}
}

// TestDistinctOn proves DISTINCT ON keeps the first row per key (ordered).
func TestDistinctOn(t *testing.T) {
	ex, done := newIdxExec(t)
	defer done()
	sess := testSession(t)

	run(t, ex, sess, "CREATE TABLE t (id INT PRIMARY KEY, grp INT, v INT)")
	run(t, ex, sess, "INSERT INTO t (id, grp, v) VALUES (1, 1, 100)")
	run(t, ex, sess, "INSERT INTO t (id, grp, v) VALUES (2, 1, 200)")
	run(t, ex, sess, "INSERT INTO t (id, grp, v) VALUES (3, 2, 300)")

	r := run(t, ex, sess, "SELECT DISTINCT ON (grp) grp, v FROM t ORDER BY grp, v")
	if len(r.Rows) != 2 {
		t.Fatalf("DISTINCT ON: want 2 groups got %d (%v)", len(r.Rows), rowsText(r))
	}
	// First of grp=1 by v ascending is v=100; grp=2 is v=300.
	if r.Rows[0][0].Text != "1" || r.Rows[0][1].Text != "100" {
		t.Fatalf("DISTINCT ON: grp 1 want first v=100 got %v", r.Rows[0])
	}
	if r.Rows[1][0].Text != "2" || r.Rows[1][1].Text != "300" {
		t.Fatalf("DISTINCT ON: grp 2 want v=300 got %v", r.Rows[1])
	}
}

// TestLateralLeftJoin proves LEFT JOIN LATERAL correlates the subquery with the
// preceding FROM row.
func TestLateralLeftJoin(t *testing.T) {
	ex, done := newIdxExec(t)
	defer done()
	sess := testSession(t)

	run(t, ex, sess, "CREATE TABLE users (id INT PRIMARY KEY, name TEXT)")
	run(t, ex, sess, "CREATE TABLE orders (id INT PRIMARY KEY, uid INT, amount INT)")
	run(t, ex, sess, "INSERT INTO users (id, name) VALUES (1, 'alice')")
	run(t, ex, sess, "INSERT INTO users (id, name) VALUES (2, 'bob')")
	run(t, ex, sess, "INSERT INTO orders (id, uid, amount) VALUES (10, 1, 50)")
	run(t, ex, sess, "INSERT INTO orders (id, uid, amount) VALUES (11, 1, 75)")

	r := run(t, ex, sess,
		"SELECT users.name, o.amount FROM users LEFT JOIN LATERAL (SELECT amount FROM orders WHERE orders.uid = users.id ORDER BY amount DESC LIMIT 1) o ON true ORDER BY users.id")
	if len(r.Rows) != 2 {
		t.Fatalf("LATERAL: want 2 rows got %d (%v)", len(r.Rows), rowsText(r))
	}
	// alice: max amount 75; bob: no orders -> NULL.
	if r.Rows[0][0].Text != "alice" || r.Rows[0][1].Text != "75" {
		t.Fatalf("LATERAL: alice want amount 75 got %v", r.Rows[0])
	}
	if r.Rows[1][0].Text != "bob" || !r.Rows[1][1].Null {
		t.Fatalf("LATERAL: bob want NULL amount got %v", r.Rows[1])
	}
}

// TestExpressionIndex proves an expression index is created and maintained
// without error across insert/update/delete.
func TestExpressionIndex(t *testing.T) {
	ex, done := newIdxExec(t)
	defer done()
	sess := testSession(t)

	run(t, ex, sess, "CREATE TABLE t (id INT PRIMARY KEY, name TEXT)")
	run(t, ex, sess, "INSERT INTO t (id, name) VALUES (1, 'Alice')")
	run(t, ex, sess, "CREATE INDEX t_lower_name ON t (lower(name))")
	// Maintenance on insert/update/delete must not error or corrupt.
	run(t, ex, sess, "INSERT INTO t (id, name) VALUES (2, 'BOB')")
	run(t, ex, sess, "UPDATE t SET name = 'Carol' WHERE id = 1")
	run(t, ex, sess, "DELETE FROM t WHERE id = 2")
	r := run(t, ex, sess, "SELECT id, name FROM t ORDER BY id")
	if len(r.Rows) != 1 || r.Rows[0][1].Text != "Carol" {
		t.Fatalf("expression index maintenance: unexpected rows %v", rowsText(r))
	}
}

// TestPartialIndex proves a partial index is created and only indexes matching
// rows, while leaving query results correct.
func TestPartialIndex(t *testing.T) {
	ex, done := newIdxExec(t)
	defer done()
	sess := testSession(t)

	run(t, ex, sess, "CREATE TABLE t (id INT PRIMARY KEY, active BOOLEAN, name TEXT)")
	run(t, ex, sess, "INSERT INTO t (id, active, name) VALUES (1, true, 'a')")
	run(t, ex, sess, "INSERT INTO t (id, active, name) VALUES (2, false, 'b')")
	run(t, ex, sess, "CREATE INDEX t_active_name ON t (name) WHERE active")
	// Inserts/updates that move rows in and out of the predicate must not error.
	run(t, ex, sess, "INSERT INTO t (id, active, name) VALUES (3, true, 'c')")
	run(t, ex, sess, "UPDATE t SET active = true WHERE id = 2")
	r := run(t, ex, sess, "SELECT id FROM t ORDER BY id")
	if len(r.Rows) != 3 {
		t.Fatalf("partial index maintenance: want 3 rows got %d", len(r.Rows))
	}
}
