// Code generated by goyacc -o sql.go -l sql.y. DO NOT EDIT.
// Code generated by goyacc. DO NOT EDIT manually.
// Source grammar: sql.y (milestone-1, ADR-008). Emits engine/internal/ast.
package parser

import __yyfmt__ "fmt"

import "github.com/cloudtasticdev/basuyudb/engine/internal/ast"

type yySymType struct {
	yys int
	str string
	ival int
	node ast.Node
	nodes []ast.Node
	resTargets []*ast.ResTarget
	resTarget *ast.ResTarget
	rangeVar *ast.RangeVar
	sortList []*ast.SortBy
	sortBy *ast.SortBy
	strs []string
	colDefs []ast.ColumnDef
	colDef ast.ColumnDef
	jt ast.JoinType
	boolVal bool
}

const IDENT = 57346
const SCONST = 57347
const ICONST = 57348
const FCONST = 57349
const OP = 57350
const COMPARE_OP = 57351
const ADD_OP = 57352
const MUL_OP = 57353
const JSON_OP = 57354
const VECTOR_OP = 57355
const STAR = 57356
const PARAM = 57357
const SELECT = 57358
const FROM = 57359
const WHERE = 57360
const AS = 57361
const JOIN = 57362
const INNER = 57363
const LEFT = 57364
const RIGHT = 57365
const FULL = 57366
const CROSS = 57367
const ON = 57368
const USING = 57369
const AND = 57370
const OR = 57371
const NOT = 57372
const NULL = 57373
const IS = 57374
const ORDER = 57375
const BY = 57376
const ASC = 57377
const DESC = 57378
const GROUP = 57379
const HAVING = 57380
const LIMIT = 57381
const OFFSET = 57382
const INSERT = 57383
const INTO = 57384
const VALUES = 57385
const UPDATE = 57386
const SET = 57387
const DELETE = 57388
const CREATE = 57389
const TABLE = 57390
const PRIMARY = 57391
const KEY = 57392
const BRANCH = 57393
const MERGE = 57394
const DROP = 57395
const TRUE = 57396
const FALSE = 57397
const DISTINCT = 57398
const TYPECAST = 57399
const UMINUS = 57400

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"IDENT",
	"SCONST",
	"ICONST",
	"FCONST",
	"OP",
	"COMPARE_OP",
	"ADD_OP",
	"MUL_OP",
	"JSON_OP",
	"VECTOR_OP",
	"STAR",
	"PARAM",
	"SELECT",
	"FROM",
	"WHERE",
	"AS",
	"JOIN",
	"INNER",
	"LEFT",
	"RIGHT",
	"FULL",
	"CROSS",
	"ON",
	"USING",
	"AND",
	"OR",
	"NOT",
	"NULL",
	"IS",
	"ORDER",
	"BY",
	"ASC",
	"DESC",
	"GROUP",
	"HAVING",
	"LIMIT",
	"OFFSET",
	"INSERT",
	"INTO",
	"VALUES",
	"UPDATE",
	"SET",
	"DELETE",
	"CREATE",
	"TABLE",
	"PRIMARY",
	"KEY",
	"BRANCH",
	"MERGE",
	"DROP",
	"TRUE",
	"FALSE",
	"DISTINCT",
	"TYPECAST",
	"UMINUS",
	"';'",
	"','",
	"'('",
	"')'",
	"'.'",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

var yyExca = [...]int16{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 87,
	20, 29,
	-2, 23,
	-1, 145,
	20, 29,
	-2, 24,
}

const yyPrivate = 57344

const yyLast = 299

var yyAct = [...]uint8{
	105, 173, 41, 104, 108, 88, 115, 87, 76, 69,
	136, 48, 183, 79, 48, 132, 23, 161, 140, 131,
	139, 33, 136, 178, 135, 46, 176, 134, 49, 50,
	80, 81, 64, 63, 61, 59, 60, 62, 132, 56,
	133, 74, 132, 121, 70, 71, 72, 42, 36, 34,
	35, 65, 66, 45, 19, 67, 33, 103, 40, 89,
	91, 92, 93, 94, 95, 96, 97, 98, 84, 21,
	59, 68, 111, 44, 39, 63, 61, 59, 60, 62,
	68, 113, 55, 31, 26, 106, 29, 27, 28, 110,
	63, 61, 59, 153, 62, 163, 47, 37, 38, 61,
	59, 83, 62, 107, 43, 102, 22, 170, 42, 36,
	34, 35, 154, 138, 45, 68, 165, 143, 32, 40,
	137, 120, 68, 166, 89, 144, 11, 156, 162, 145,
	100, 99, 130, 149, 44, 39, 147, 68, 150, 85,
	167, 168, 146, 80, 157, 68, 128, 152, 158, 89,
	89, 12, 159, 160, 13, 82, 14, 15, 37, 38,
	25, 129, 16, 17, 112, 43, 171, 174, 175, 109,
	24, 177, 42, 36, 34, 35, 116, 151, 45, 174,
	182, 181, 148, 40, 64, 63, 61, 59, 60, 62,
	124, 125, 126, 127, 123, 141, 77, 118, 44, 39,
	117, 101, 90, 65, 66, 78, 53, 67, 52, 58,
	179, 180, 51, 18, 64, 63, 61, 59, 60, 62,
	1, 20, 37, 38, 57, 122, 114, 73, 172, 43,
	155, 75, 68, 65, 66, 30, 119, 67, 64, 63,
	61, 59, 60, 62, 64, 63, 61, 59, 60, 62,
	64, 63, 61, 59, 60, 62, 86, 65, 66, 54,
	169, 67, 68, 65, 164, 142, 10, 67, 9, 8,
	7, 6, 5, 67, 4, 3, 2, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 68, 0, 0, 0,
	0, 0, 68, 0, 0, 0, 0, 0, 68,
}

var yyPact = [...]int16{
	110, -1000, -5, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, 13, 64, 166, 143, 36, 37, 35, -1000, -1000,
	104, -1000, 166, 51, -49, 166, 166, 208, 204, 202,
	22, -1000, -1000, 205, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -52, 168, 168, 168, -20, 192, 201, 125,
	-30, 138, 59, -1000, 125, 104, 166, 198, -1000, 168,
	168, 168, 168, 168, 168, 168, 168, 100, 197, 43,
	23, 241, -1000, 60, 165, 12, -1000, 155, -1000, -1000,
	168, 172, 196, 193, 84, -1000, -17, 169, -1000, 142,
	-1000, 14, 80, 58, 58, 88, 65, 241, 235, -1000,
	101, -1000, -1000, -43, -22, 229, -1000, -34, -38, -1000,
	-1000, 192, 168, 229, -42, -1000, 191, -1000, -1000, 79,
	91, 166, 122, 116, -1000, -1000, -1000, -1000, -1000, 178,
	-1000, -1000, 168, -1000, 168, -1000, 173, -1000, 229, -1000,
	172, 63, 94, 168, 168, 169, 166, 166, -1000, 229,
	-45, -1000, -1000, 97, 45, 77, 89, 229, -18, 114,
	-1000, -1000, -1000, -1000, 67, 168, 168, 168, -35, -1000,
	168, 229, -37, -1000, 175, 229, 165, 229, 168, -1000,
	-1000, -50, -1000, -1000,
}

var yyPgo = [...]int16{
	0, 276, 275, 274, 272, 271, 270, 269, 268, 266,
	0, 5, 7, 13, 265, 264, 260, 259, 256, 3,
	236, 235, 231, 83, 8, 2, 230, 228, 1, 4,
	227, 226, 6, 225, 221, 220, 213,
}

var yyR1 = [...]int8{
	0, 35, 36, 36, 1, 1, 1, 1, 1, 1,
	1, 1, 2, 34, 34, 21, 21, 23, 23, 23,
	23, 17, 17, 18, 18, 12, 12, 12, 12, 33,
	33, 33, 33, 33, 11, 11, 11, 13, 13, 20,
	20, 14, 14, 26, 26, 27, 27, 28, 28, 28,
	15, 15, 16, 16, 3, 30, 30, 4, 22, 22,
	24, 5, 6, 31, 31, 32, 32, 32, 7, 7,
	8, 8, 9, 19, 19, 10, 10, 10, 10, 10,
	10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
	10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
	25, 25, 29, 29,
}

var yyR2 = [...]int8{
	0, 2, 0, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 10, 0, 1, 1, 3, 1, 1, 3,
	2, 0, 2, 1, 3, 1, 6, 8, 4, 0,
	1, 1, 1, 1, 1, 2, 3, 0, 2, 0,
	3, 0, 2, 0, 3, 1, 3, 1, 2, 2,
	0, 2, 0, 2, 8, 0, 3, 5, 1, 3,
	3, 4, 6, 1, 3, 2, 4, 4, 3, 5,
	5, 3, 3, 1, 3, 1, 1, 1, 1, 1,
	1, 1, 1, 3, 4, 4, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 2, 3, 4, 3, 2,
	1, 3, 1, 3,
}

var yyChk = [...]int16{
	-1000, -35, -1, -2, -3, -4, -5, -6, -7, -8,
	-9, 16, 41, 44, 46, 47, 52, 53, -36, 59,
	-34, 56, 42, -25, 4, 17, 48, 51, 51, 51,
	-21, -23, 14, -10, 6, 7, 5, 54, 55, 31,
	15, -25, 4, 61, 30, 10, -25, 45, 63, -25,
	-25, 4, 4, 4, -17, 60, 17, 19, 4, 12,
	13, 11, 14, 10, 9, 28, 29, 32, 57, 61,
	-10, -10, -10, -30, 61, -22, -24, 4, 4, -13,
	18, 61, 17, 42, -13, -23, -18, -12, -11, -25,
	4, -10, -10, -10, -10, -10, -10, -10, -10, 31,
	30, 4, 62, 14, -19, -10, 62, 43, -29, 4,
	-13, 60, 9, -10, -31, -32, 4, 4, 4, -20,
	37, 60, -33, 25, 21, 22, 23, 24, 4, 19,
	31, 62, 60, 62, 61, 62, 60, -24, -10, 62,
	60, 4, -14, 38, 34, -12, 20, 20, 4, -10,
	-19, 4, -32, 30, 49, -26, 33, -10, -19, -11,
	-11, 62, 31, 50, -15, 39, 34, 26, 27, -16,
	40, -10, -27, -28, -10, -10, 61, -10, 60, 35,
	36, -29, -28, 62,
}

var yyDef = [...]int8{
	0, -2, 2, 4, 5, 6, 7, 8, 9, 10,
	11, 13, 0, 0, 0, 0, 0, 0, 1, 3,
	0, 14, 0, 0, 100, 0, 0, 0, 0, 0,
	21, 15, 17, 18, 75, 76, 77, 78, 79, 80,
	81, 82, 100, 0, 0, 0, 55, 0, 0, 37,
	0, 68, 71, 72, 37, 0, 0, 0, 20, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 95, 99, 0, 0, 37, 58, 0, 101, 61,
	0, 0, 0, 0, 39, 16, 22, -2, 25, 34,
	19, 87, 88, 89, 90, 91, 92, 93, 94, 96,
	0, 98, 83, 0, 0, 73, 86, 0, 0, 102,
	57, 0, 0, 38, 0, 63, 0, 69, 70, 41,
	0, 0, 0, 0, 30, 31, 32, 33, 35, 0,
	97, 84, 0, 85, 0, 56, 0, 59, 60, 62,
	0, 65, 43, 0, 0, -2, 0, 0, 36, 74,
	0, 103, 64, 0, 0, 50, 0, 42, 40, 0,
	28, 54, 66, 67, 52, 0, 0, 0, 0, 12,
	0, 51, 44, 45, 47, 26, 0, 53, 0, 48,
	49, 0, 46, 27,
}

var yyTok1 = [...]int8{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	61, 62, 3, 3, 60, 3, 63, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 59,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
	52, 53, 54, 55, 56, 57, 58,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg string
}{}

/*	parser for yacc output	*/

var (
	yyDebug = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval yySymType
	stack [yyInitialStackSize]yySymType
	char int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0 /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yylex.(*lexer).result = yyDollar[1].node
		}
	case 2:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
		}
	case 3:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
		}
	case 4:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 5:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 6:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 7:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 8:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 9:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 10:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 11:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 12:
		yyDollar = yyS[yypt-10 : yypt+1]
		{
			yyVAL.node = &ast.SelectStmt{
				TargetList: yyDollar[3].resTargets,
				FromClause: yyDollar[4].nodes,
				WhereClause: yyDollar[5].node,
				GroupClause: yyDollar[6].nodes,
				HavingClause: yyDollar[7].node,
				SortClause: yyDollar[8].sortList,
				LimitCount: yyDollar[9].node,
				LimitOffset: yyDollar[10].node,
			}
		}
	case 13:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.boolVal = false
		}
	case 14:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.boolVal = true
		}
	case 15:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.resTargets = []*ast.ResTarget{yyDollar[1].resTarget}
		}
	case 16:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.resTargets = append(yyDollar[1].resTargets, yyDollar[3].resTarget)
		}
	case 17:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.resTarget = &ast.ResTarget{Val: &ast.A_Star{}}
		}
	case 18:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.resTarget = &ast.ResTarget{Val: yyDollar[1].node}
		}
	case 19:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.resTarget = &ast.ResTarget{Name: yyDollar[3].str, Val: yyDollar[1].node}
		}
	case 20:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.resTarget = &ast.ResTarget{Name: yyDollar[2].str, Val: yyDollar[1].node}
		}
	case 21:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.nodes = nil
		}
	case 22:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.nodes = yyDollar[2].nodes
		}
	case 23:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.nodes = []ast.Node{yyDollar[1].node}
		}
	case 24:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.nodes = append(yyDollar[1].nodes, yyDollar[3].node)
		}
	case 25:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 26:
		yyDollar = yyS[yypt-6 : yypt+1]
		{
			yyVAL.node = &ast.JoinExpr{JoinType: yyDollar[2].jt, Larg: yyDollar[1].node, Rarg: yyDollar[4].node, Quals: yyDollar[6].node}
		}
	case 27:
		yyDollar = yyS[yypt-8 : yypt+1]
		{
			yyVAL.node = &ast.JoinExpr{JoinType: yyDollar[2].jt, Larg: yyDollar[1].node, Rarg: yyDollar[4].node, UsingCols: yyDollar[7].strs}
		}
	case 28:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = &ast.JoinExpr{JoinType: ast.JOIN_CROSS, Larg: yyDollar[1].node, Rarg: yyDollar[4].node}
		}
	case 29:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.jt = ast.JOIN_INNER
		}
	case 30:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.jt = ast.JOIN_INNER
		}
	case 31:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.jt = ast.JOIN_LEFT
		}
	case 32:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.jt = ast.JOIN_RIGHT
		}
	case 33:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.jt = ast.JOIN_FULL
		}
	case 34:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].rangeVar
		}
	case 35:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyDollar[1].rangeVar.Alias = &ast.Alias{AliasName: yyDollar[2].str}
			yyVAL.node = yyDollar[1].rangeVar
		}
	case 36:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyDollar[1].rangeVar.Alias = &ast.Alias{AliasName: yyDollar[3].str}
			yyVAL.node = yyDollar[1].rangeVar
		}
	case 37:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.node = nil
		}
	case 38:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.node = yyDollar[2].node
		}
	case 39:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.nodes = nil
		}
	case 40:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.nodes = yyDollar[3].nodes
		}
	case 41:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.node = nil
		}
	case 42:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.node = yyDollar[2].node
		}
	case 43:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.sortList = nil
		}
	case 44:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.sortList = yyDollar[3].sortList
		}
	case 45:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.sortList = []*ast.SortBy{yyDollar[1].sortBy}
		}
	case 46:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.sortList = append(yyDollar[1].sortList, yyDollar[3].sortBy)
		}
	case 47:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.sortBy = &ast.SortBy{Node: yyDollar[1].node, SortDir: 0}
		}
	case 48:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.sortBy = &ast.SortBy{Node: yyDollar[1].node, SortDir: 1}
		}
	case 49:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.sortBy = &ast.SortBy{Node: yyDollar[1].node, SortDir: 2}
		}
	case 50:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.node = nil
		}
	case 51:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.node = yyDollar[2].node
		}
	case 52:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.node = nil
		}
	case 53:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.node = yyDollar[2].node
		}
	case 54:
		yyDollar = yyS[yypt-8 : yypt+1]
		{
			cols := make([]*ast.ResTarget, 0, len(yyDollar[4].strs))
			for _, c := range yyDollar[4].strs {
				cols = append(cols, &ast.ResTarget{Name: c})
			}
			yyVAL.node = &ast.InsertStmt{
				Relation: yyDollar[3].rangeVar,
				Cols: cols,
				SelectStmt: &ast.SelectStmt{TargetList: valuesToTargets(yyDollar[7].nodes)},
			}
		}
	case 55:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.strs = nil
		}
	case 56:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.strs = yyDollar[2].strs
		}
	case 57:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			yyVAL.node = &ast.UpdateStmt{Relation: yyDollar[2].rangeVar, TargetList: yyDollar[4].resTargets, WhereClause: yyDollar[5].node}
		}
	case 58:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.resTargets = []*ast.ResTarget{yyDollar[1].resTarget}
		}
	case 59:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.resTargets = append(yyDollar[1].resTargets, yyDollar[3].resTarget)
		}
	case 60:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			if yyDollar[2].str != "=" {
				yylex.Error("expected = in SET assignment")
			}
			yyVAL.resTarget = &ast.ResTarget{Name: yyDollar[1].str, Val: yyDollar[3].node}
		}
	case 61:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = &ast.DeleteStmt{Relation: yyDollar[3].rangeVar, WhereClause: yyDollar[4].node}
		}
	case 62:
		yyDollar = yyS[yypt-6 : yypt+1]
		{
			yyVAL.node = &ast.CreateStmt{Relation: yyDollar[3].rangeVar, TableElts: yyDollar[5].colDefs}
		}
	case 63:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.colDefs = []ast.ColumnDef{yyDollar[1].colDef}
		}
	case 64:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.colDefs = append(yyDollar[1].colDefs, yyDollar[3].colDef)
		}
	case 65:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.colDef = ast.ColumnDef{ColName: yyDollar[1].str, TypeName: yyDollar[2].str}
		}
	case 66:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.colDef = ast.ColumnDef{ColName: yyDollar[1].str, TypeName: yyDollar[2].str, NotNull: true}
		}
	case 67:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.colDef = ast.ColumnDef{ColName: yyDollar[1].str, TypeName: yyDollar[2].str, PrimaryKey: true, NotNull: true}
		}
	case 68:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.CreateBranchStmt{BranchName: yyDollar[3].str, FromBranch: "main"}
		}
	case 69:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			yyVAL.node = &ast.CreateBranchStmt{BranchName: yyDollar[3].str, FromBranch: yyDollar[5].str}
		}
	case 70:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			yyVAL.node = &ast.MergeBranchStmt{SourceBranch: yyDollar[3].str, TargetBranch: yyDollar[5].str}
		}
	case 71:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.MergeBranchStmt{SourceBranch: yyDollar[3].str, TargetBranch: "main"}
		}
	case 72:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.DropBranchStmt{BranchName: yyDollar[3].str}
		}
	case 73:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.nodes = []ast.Node{yyDollar[1].node}
		}
	case 74:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.nodes = append(yyDollar[1].nodes, yyDollar[3].node)
		}
	case 75:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = &ast.A_Const{Type: ast.ConstInt, Val: yyDollar[1].str}
		}
	case 76:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = &ast.A_Const{Type: ast.ConstFloat, Val: yyDollar[1].str}
		}
	case 77:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = &ast.A_Const{Type: ast.ConstString, Val: yyDollar[1].str}
		}
	case 78:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = &ast.A_Const{Type: ast.ConstBool, Val: "true"}
		}
	case 79:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = &ast.A_Const{Type: ast.ConstBool, Val: "false"}
		}
	case 80:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = &ast.A_Const{Type: ast.ConstNull}
		}
	case 81:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = &ast.ParamRef{Number: yyDollar[1].ival}
		}
	case 82:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = colRefFromRangeVar(yyDollar[1].rangeVar)
		}
	case 83:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.FuncCall{FuncName: []string{yyDollar[1].str}}
		}
	case 84:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = &ast.FuncCall{FuncName: []string{yyDollar[1].str}, AggStar: true}
		}
	case 85:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = &ast.FuncCall{FuncName: []string{yyDollar[1].str}, Args: yyDollar[3].nodes}
		}
	case 86:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = yyDollar[2].node
		}
	case 87:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.A_Expr{Kind: ast.AEXPR_OP, Name: yyDollar[2].str, Lexpr: yyDollar[1].node, Rexpr: yyDollar[3].node}
		}
	case 88:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.A_Expr{Kind: ast.AEXPR_OP, Name: yyDollar[2].str, Lexpr: yyDollar[1].node, Rexpr: yyDollar[3].node}
		}
	case 89:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.A_Expr{Kind: ast.AEXPR_OP, Name: yyDollar[2].str, Lexpr: yyDollar[1].node, Rexpr: yyDollar[3].node}
		}
	case 90:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.A_Expr{Kind: ast.AEXPR_OP, Name: "*", Lexpr: yyDollar[1].node, Rexpr: yyDollar[3].node}
		}
	case 91:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.A_Expr{Kind: ast.AEXPR_OP, Name: yyDollar[2].str, Lexpr: yyDollar[1].node, Rexpr: yyDollar[3].node}
		}
	case 92:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.A_Expr{Kind: ast.AEXPR_OP, Name: yyDollar[2].str, Lexpr: yyDollar[1].node, Rexpr: yyDollar[3].node}
		}
	case 93:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.BoolExpr{Op: ast.AND_EXPR, Args: []ast.Node{yyDollar[1].node, yyDollar[3].node}}
		}
	case 94:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.BoolExpr{Op: ast.OR_EXPR, Args: []ast.Node{yyDollar[1].node, yyDollar[3].node}}
		}
	case 95:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.node = &ast.BoolExpr{Op: ast.NOT_EXPR, Args: []ast.Node{yyDollar[2].node}}
		}
	case 96:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.NullTest{Arg: yyDollar[1].node, TestNull: true}
		}
	case 97:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = &ast.NullTest{Arg: yyDollar[1].node, TestNull: false}
		}
	case 98:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.TypeCast{Arg: yyDollar[1].node, TypeName: yyDollar[3].str}
		}
	case 99:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.node = &ast.A_Expr{Kind: ast.AEXPR_OP, Name: yyDollar[1].str, Rexpr: yyDollar[2].node}
		}
	case 100:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.rangeVar = &ast.RangeVar{RelName: yyDollar[1].str}
		}
	case 101:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.rangeVar = &ast.RangeVar{SchemaName: yyDollar[1].str, RelName: yyDollar[3].str}
		}
	case 102:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.strs = []string{yyDollar[1].str}
		}
	case 103:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.strs = append(yyDollar[1].strs, yyDollar[3].str)
		}
	}
	goto yystack /* stack new state and value */
}
