// Code generated by goyacc -o sql.go -l sql.y. DO NOT EDIT.
// Code generated by goyacc. DO NOT EDIT manually.
// Source grammar: sql.y (milestone-1, ADR-008). Emits engine/internal/ast.
package parser

import __yyfmt__ "fmt"

import "github.com/cloudtasticdev/basuyudb/engine/internal/ast"

type yySymType struct {
	yys        int
	str        string
	ival       int
	node       ast.Node
	nodes      []ast.Node
	resTargets []*ast.ResTarget
	resTarget  *ast.ResTarget
	rangeVar   *ast.RangeVar
	sortList   []*ast.SortBy
	sortBy     *ast.SortBy
	strs       []string
	colDefs    []ast.ColumnDef
	colDef     ast.ColumnDef
	jt         ast.JoinType
	boolVal    bool
}

const IDENT = 57346
const SCONST = 57347
const ICONST = 57348
const FCONST = 57349
const OP = 57350
const COMPARE_OP = 57351
const ADD_OP = 57352
const MUL_OP = 57353
const JSON_OP = 57354
const VECTOR_OP = 57355
const STAR = 57356
const PARAM = 57357
const SELECT = 57358
const FROM = 57359
const WHERE = 57360
const AS = 57361
const JOIN = 57362
const INNER = 57363
const LEFT = 57364
const RIGHT = 57365
const FULL = 57366
const CROSS = 57367
const ON = 57368
const USING = 57369
const AND = 57370
const OR = 57371
const NOT = 57372
const NULL = 57373
const IS = 57374
const ORDER = 57375
const BY = 57376
const ASC = 57377
const DESC = 57378
const GROUP = 57379
const HAVING = 57380
const LIMIT = 57381
const OFFSET = 57382
const INSERT = 57383
const INTO = 57384
const VALUES = 57385
const UPDATE = 57386
const SET = 57387
const DELETE = 57388
const CREATE = 57389
const TABLE = 57390
const PRIMARY = 57391
const KEY = 57392
const INDEX = 57393
const UNIQUE = 57394
const BRANCH = 57395
const MERGE = 57396
const DROP = 57397
const TRUE = 57398
const FALSE = 57399
const DISTINCT = 57400
const TYPECAST = 57401
const UMINUS = 57402

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"IDENT",
	"SCONST",
	"ICONST",
	"FCONST",
	"OP",
	"COMPARE_OP",
	"ADD_OP",
	"MUL_OP",
	"JSON_OP",
	"VECTOR_OP",
	"STAR",
	"PARAM",
	"SELECT",
	"FROM",
	"WHERE",
	"AS",
	"JOIN",
	"INNER",
	"LEFT",
	"RIGHT",
	"FULL",
	"CROSS",
	"ON",
	"USING",
	"AND",
	"OR",
	"NOT",
	"NULL",
	"IS",
	"ORDER",
	"BY",
	"ASC",
	"DESC",
	"GROUP",
	"HAVING",
	"LIMIT",
	"OFFSET",
	"INSERT",
	"INTO",
	"VALUES",
	"UPDATE",
	"SET",
	"DELETE",
	"CREATE",
	"TABLE",
	"PRIMARY",
	"KEY",
	"INDEX",
	"UNIQUE",
	"BRANCH",
	"MERGE",
	"DROP",
	"TRUE",
	"FALSE",
	"DISTINCT",
	"TYPECAST",
	"UMINUS",
	"';'",
	"','",
	"'('",
	"')'",
	"'.'",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

var yyExca = [...]int16{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 94,
	20, 30,
	-2, 24,
	-1, 156,
	20, 30,
	-2, 25,
}

const yyPrivate = 57344

const yyLast = 298

var yyAct = [...]uint8{
	112, 115, 189, 95, 111, 94, 122, 81, 74, 145,
	51, 199, 44, 84, 145, 145, 184, 177, 141, 149,
	174, 148, 36, 145, 141, 144, 142, 24, 51, 140,
	192, 45, 39, 37, 38, 167, 49, 48, 151, 52,
	53, 110, 43, 143, 85, 86, 79, 75, 76, 77,
	68, 66, 64, 65, 67, 194, 61, 47, 42, 141,
	130, 36, 20, 64, 73, 98, 99, 100, 101, 102,
	103, 104, 105, 91, 96, 22, 34, 27, 32, 55,
	28, 29, 30, 40, 41, 31, 120, 176, 118, 164,
	46, 109, 50, 114, 117, 90, 23, 186, 154, 73,
	124, 60, 69, 68, 66, 64, 65, 67, 165, 180,
	73, 129, 181, 45, 39, 37, 38, 155, 169, 48,
	147, 70, 71, 35, 43, 72, 146, 69, 68, 66,
	64, 65, 67, 107, 106, 175, 156, 92, 152, 47,
	42, 139, 160, 96, 158, 125, 70, 71, 161, 87,
	72, 157, 73, 166, 85, 170, 163, 113, 182, 183,
	171, 172, 173, 137, 89, 40, 41, 26, 116, 178,
	96, 96, 46, 45, 39, 37, 38, 73, 138, 48,
	119, 187, 190, 191, 43, 25, 123, 193, 69, 68,
	66, 64, 65, 67, 197, 190, 19, 198, 162, 47,
	42, 69, 68, 66, 64, 65, 67, 70, 71, 159,
	150, 72, 63, 82, 195, 196, 127, 69, 68, 66,
	64, 65, 67, 1, 72, 40, 41, 62, 126, 68,
	66, 64, 46, 67, 108, 21, 70, 71, 73, 97,
	72, 69, 68, 66, 64, 65, 67, 66, 64, 12,
	67, 73, 133, 134, 135, 136, 132, 88, 83, 58,
	70, 57, 56, 54, 72, 131, 121, 73, 78, 188,
	168, 80, 33, 128, 13, 93, 59, 14, 73, 15,
	16, 185, 179, 153, 11, 10, 9, 17, 18, 8,
	7, 73, 6, 5, 4, 73, 3, 2,
}

var yyPact = [...]int16{
	233, -1000, 1, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, 17, 54, 181, 150, 29, 32, 25, -1000,
	-1000, 109, -1000, 181, 47, -37, 181, 181, 259, 28,
	258, 257, 255, 39, -1000, -1000, 208, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -55, 169, 169, 169, -17,
	209, 254, 136, -18, 123, 253, 147, 53, -1000, 136,
	109, 181, 235, -1000, 169, 169, 169, 169, 169, 169,
	169, 169, 103, 230, 27, 93, 192, -1000, 50, 164,
	26, -1000, 171, -1000, -1000, 169, 182, 181, 119, 224,
	212, 74, -1000, -2, 231, -1000, 159, -1000, 5, 219,
	51, 51, 236, 40, 192, 232, -1000, 110, -1000, -1000,
	-35, -38, 118, -1000, -20, -39, -1000, -1000, 209, 169,
	118, -43, -1000, 206, -25, 181, -1000, -1000, 60, 83,
	181, 131, 124, -1000, -1000, -1000, -1000, -1000, 205, -1000,
	-1000, 169, -1000, 169, -1000, 194, -1000, 118, -1000, 182,
	59, 164, -28, 85, 169, 169, 231, 181, 181, -1000,
	118, -44, -1000, -1000, 104, 37, -47, 164, 70, 78,
	118, -3, 132, -1000, -1000, -1000, -1000, -1000, -48, 57,
	169, 169, 169, -33, -1000, -1000, 169, 118, -7, -1000,
	179, 118, 164, 118, 169, -1000, -1000, -53, -1000, -1000,
}

var yyPgo = [...]int16{
	0, 297, 296, 294, 293, 292, 290, 289, 286, 285,
	284, 0, 3, 5, 13, 283, 282, 281, 276, 275,
	4, 273, 272, 271, 76, 7, 12, 270, 269, 2,
	1, 268, 266, 6, 265, 235, 223, 196,
}

var yyR1 = [...]int8{
	0, 36, 37, 37, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 2, 35, 35, 22, 22, 24, 24,
	24, 24, 18, 18, 19, 19, 13, 13, 13, 13,
	34, 34, 34, 34, 34, 12, 12, 12, 14, 14,
	21, 21, 15, 15, 27, 27, 28, 28, 29, 29,
	29, 16, 16, 17, 17, 3, 31, 31, 4, 23,
	23, 25, 5, 6, 7, 7, 32, 32, 33, 33,
	33, 8, 8, 9, 9, 10, 20, 20, 11, 11,
	11, 11, 11, 11, 11, 11, 11, 11, 11, 11,
	11, 11, 11, 11, 11, 11, 11, 11, 11, 11,
	11, 11, 11, 26, 26, 30, 30,
}

var yyR2 = [...]int8{
	0, 2, 0, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 10, 0, 1, 1, 3, 1, 1,
	3, 2, 0, 2, 1, 3, 1, 6, 8, 4,
	0, 1, 1, 1, 1, 1, 2, 3, 0, 2,
	0, 3, 0, 2, 0, 3, 1, 3, 1, 2,
	2, 0, 2, 0, 2, 8, 0, 3, 5, 1,
	3, 3, 4, 6, 8, 9, 1, 3, 2, 4,
	4, 3, 5, 5, 3, 3, 1, 3, 1, 1,
	1, 1, 1, 1, 1, 1, 3, 4, 4, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 2, 3,
	4, 3, 2, 1, 3, 1, 3,
}

var yyChk = [...]int16{
	-1000, -36, -1, -2, -3, -4, -5, -6, -7, -8,
	-9, -10, 16, 41, 44, 46, 47, 54, 55, -37,
	61, -35, 58, 42, -26, 4, 17, 48, 51, 52,
	53, 53, 53, -22, -24, 14, -11, 6, 7, 5,
	56, 57, 31, 15, -26, 4, 63, 30, 10, -26,
	45, 65, -26, -26, 4, 51, 4, 4, 4, -18,
	62, 17, 19, 4, 12, 13, 11, 14, 10, 9,
	28, 29, 32, 59, 63, -11, -11, -11, -31, 63,
	-23, -25, 4, 4, -14, 18, 63, 26, 4, 17,
	42, -14, -24, -19, -13, -12, -26, 4, -11, -11,
	-11, -11, -11, -11, -11, -11, 31, 30, 4, 64,
	14, -20, -11, 64, 43, -30, 4, -14, 62, 9,
	-11, -32, -33, 4, -26, 26, 4, 4, -21, 37,
	62, -34, 25, 21, 22, 23, 24, 4, 19, 31,
	64, 62, 64, 63, 64, 62, -25, -11, 64, 62,
	4, 63, -26, -15, 38, 34, -13, 20, 20, 4,
	-11, -20, 4, -33, 30, 49, -30, 63, -27, 33,
	-11, -20, -12, -12, 64, 31, 50, 64, -30, -16,
	39, 34, 26, 27, 64, -17, 40, -11, -28, -29,
	-11, -11, 63, -11, 62, 35, 36, -30, -29, 64,
}

var yyDef = [...]int8{
	0, -2, 2, 4, 5, 6, 7, 8, 9, 10,
	11, 12, 14, 0, 0, 0, 0, 0, 0, 1,
	3, 0, 15, 0, 0, 103, 0, 0, 0, 0,
	0, 0, 0, 22, 16, 18, 19, 78, 79, 80,
	81, 82, 83, 84, 85, 103, 0, 0, 0, 56,
	0, 0, 38, 0, 0, 0, 71, 74, 75, 38,
	0, 0, 0, 21, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 98, 102, 0, 0,
	38, 59, 0, 104, 62, 0, 0, 0, 0, 0,
	0, 40, 17, 23, -2, 26, 35, 20, 90, 91,
	92, 93, 94, 95, 96, 97, 99, 0, 101, 86,
	0, 0, 76, 89, 0, 0, 105, 58, 0, 0,
	39, 0, 66, 0, 0, 0, 72, 73, 42, 0,
	0, 0, 0, 31, 32, 33, 34, 36, 0, 100,
	87, 0, 88, 0, 57, 0, 60, 61, 63, 0,
	68, 0, 0, 44, 0, 0, -2, 0, 0, 37,
	77, 0, 106, 67, 0, 0, 0, 0, 51, 0,
	43, 41, 0, 29, 55, 69, 70, 64, 0, 53,
	0, 0, 0, 0, 65, 13, 0, 52, 45, 46,
	48, 27, 0, 54, 0, 49, 50, 0, 47, 28,
}

var yyTok1 = [...]int8{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	63, 64, 3, 3, 62, 3, 65, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 61,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
	52, 53, 54, 55, 56, 57, 58, 59, 60,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yylex.(*lexer).result = yyDollar[1].node
		}
	case 2:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
		}
	case 3:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
		}
	case 4:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 5:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 6:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 7:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 8:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 9:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 10:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 11:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 12:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 13:
		yyDollar = yyS[yypt-10 : yypt+1]
		{
			yyVAL.node = &ast.SelectStmt{
				TargetList:   yyDollar[3].resTargets,
				FromClause:   yyDollar[4].nodes,
				WhereClause:  yyDollar[5].node,
				GroupClause:  yyDollar[6].nodes,
				HavingClause: yyDollar[7].node,
				SortClause:   yyDollar[8].sortList,
				LimitCount:   yyDollar[9].node,
				LimitOffset:  yyDollar[10].node,
			}
		}
	case 14:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.boolVal = false
		}
	case 15:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.boolVal = true
		}
	case 16:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.resTargets = []*ast.ResTarget{yyDollar[1].resTarget}
		}
	case 17:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.resTargets = append(yyDollar[1].resTargets, yyDollar[3].resTarget)
		}
	case 18:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.resTarget = &ast.ResTarget{Val: &ast.A_Star{}}
		}
	case 19:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.resTarget = &ast.ResTarget{Val: yyDollar[1].node}
		}
	case 20:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.resTarget = &ast.ResTarget{Name: yyDollar[3].str, Val: yyDollar[1].node}
		}
	case 21:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.resTarget = &ast.ResTarget{Name: yyDollar[2].str, Val: yyDollar[1].node}
		}
	case 22:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.nodes = nil
		}
	case 23:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.nodes = yyDollar[2].nodes
		}
	case 24:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.nodes = []ast.Node{yyDollar[1].node}
		}
	case 25:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.nodes = append(yyDollar[1].nodes, yyDollar[3].node)
		}
	case 26:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].node
		}
	case 27:
		yyDollar = yyS[yypt-6 : yypt+1]
		{
			yyVAL.node = &ast.JoinExpr{JoinType: yyDollar[2].jt, Larg: yyDollar[1].node, Rarg: yyDollar[4].node, Quals: yyDollar[6].node}
		}
	case 28:
		yyDollar = yyS[yypt-8 : yypt+1]
		{
			yyVAL.node = &ast.JoinExpr{JoinType: yyDollar[2].jt, Larg: yyDollar[1].node, Rarg: yyDollar[4].node, UsingCols: yyDollar[7].strs}
		}
	case 29:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = &ast.JoinExpr{JoinType: ast.JOIN_CROSS, Larg: yyDollar[1].node, Rarg: yyDollar[4].node}
		}
	case 30:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.jt = ast.JOIN_INNER
		}
	case 31:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.jt = ast.JOIN_INNER
		}
	case 32:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.jt = ast.JOIN_LEFT
		}
	case 33:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.jt = ast.JOIN_RIGHT
		}
	case 34:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.jt = ast.JOIN_FULL
		}
	case 35:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = yyDollar[1].rangeVar
		}
	case 36:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyDollar[1].rangeVar.Alias = &ast.Alias{AliasName: yyDollar[2].str}
			yyVAL.node = yyDollar[1].rangeVar
		}
	case 37:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyDollar[1].rangeVar.Alias = &ast.Alias{AliasName: yyDollar[3].str}
			yyVAL.node = yyDollar[1].rangeVar
		}
	case 38:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.node = nil
		}
	case 39:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.node = yyDollar[2].node
		}
	case 40:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.nodes = nil
		}
	case 41:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.nodes = yyDollar[3].nodes
		}
	case 42:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.node = nil
		}
	case 43:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.node = yyDollar[2].node
		}
	case 44:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.sortList = nil
		}
	case 45:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.sortList = yyDollar[3].sortList
		}
	case 46:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.sortList = []*ast.SortBy{yyDollar[1].sortBy}
		}
	case 47:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.sortList = append(yyDollar[1].sortList, yyDollar[3].sortBy)
		}
	case 48:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.sortBy = &ast.SortBy{Node: yyDollar[1].node, SortDir: 0}
		}
	case 49:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.sortBy = &ast.SortBy{Node: yyDollar[1].node, SortDir: 1}
		}
	case 50:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.sortBy = &ast.SortBy{Node: yyDollar[1].node, SortDir: 2}
		}
	case 51:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.node = nil
		}
	case 52:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.node = yyDollar[2].node
		}
	case 53:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.node = nil
		}
	case 54:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.node = yyDollar[2].node
		}
	case 55:
		yyDollar = yyS[yypt-8 : yypt+1]
		{
			cols := make([]*ast.ResTarget, 0, len(yyDollar[4].strs))
			for _, c := range yyDollar[4].strs {
				cols = append(cols, &ast.ResTarget{Name: c})
			}
			yyVAL.node = &ast.InsertStmt{
				Relation:   yyDollar[3].rangeVar,
				Cols:       cols,
				SelectStmt: &ast.SelectStmt{TargetList: valuesToTargets(yyDollar[7].nodes)},
			}
		}
	case 56:
		yyDollar = yyS[yypt-0 : yypt+1]
		{
			yyVAL.strs = nil
		}
	case 57:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.strs = yyDollar[2].strs
		}
	case 58:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			yyVAL.node = &ast.UpdateStmt{Relation: yyDollar[2].rangeVar, TargetList: yyDollar[4].resTargets, WhereClause: yyDollar[5].node}
		}
	case 59:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.resTargets = []*ast.ResTarget{yyDollar[1].resTarget}
		}
	case 60:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.resTargets = append(yyDollar[1].resTargets, yyDollar[3].resTarget)
		}
	case 61:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			if yyDollar[2].str != "=" {
				yylex.Error("expected = in SET assignment")
			}
			yyVAL.resTarget = &ast.ResTarget{Name: yyDollar[1].str, Val: yyDollar[3].node}
		}
	case 62:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = &ast.DeleteStmt{Relation: yyDollar[3].rangeVar, WhereClause: yyDollar[4].node}
		}
	case 63:
		yyDollar = yyS[yypt-6 : yypt+1]
		{
			yyVAL.node = &ast.CreateStmt{Relation: yyDollar[3].rangeVar, TableElts: yyDollar[5].colDefs}
		}
	case 64:
		yyDollar = yyS[yypt-8 : yypt+1]
		{
			yyVAL.node = &ast.IndexStmt{Name: yyDollar[3].str, Table: yyDollar[5].rangeVar.RelName, Columns: yyDollar[7].strs}
		}
	case 65:
		yyDollar = yyS[yypt-9 : yypt+1]
		{
			yyVAL.node = &ast.IndexStmt{Name: yyDollar[4].str, Table: yyDollar[6].rangeVar.RelName, Columns: yyDollar[8].strs, Unique: true}
		}
	case 66:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.colDefs = []ast.ColumnDef{yyDollar[1].colDef}
		}
	case 67:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.colDefs = append(yyDollar[1].colDefs, yyDollar[3].colDef)
		}
	case 68:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.colDef = ast.ColumnDef{ColName: yyDollar[1].str, TypeName: yyDollar[2].str}
		}
	case 69:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.colDef = ast.ColumnDef{ColName: yyDollar[1].str, TypeName: yyDollar[2].str, NotNull: true}
		}
	case 70:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.colDef = ast.ColumnDef{ColName: yyDollar[1].str, TypeName: yyDollar[2].str, PrimaryKey: true, NotNull: true}
		}
	case 71:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.CreateBranchStmt{BranchName: yyDollar[3].str, FromBranch: "main"}
		}
	case 72:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			yyVAL.node = &ast.CreateBranchStmt{BranchName: yyDollar[3].str, FromBranch: yyDollar[5].str}
		}
	case 73:
		yyDollar = yyS[yypt-5 : yypt+1]
		{
			yyVAL.node = &ast.MergeBranchStmt{SourceBranch: yyDollar[3].str, TargetBranch: yyDollar[5].str}
		}
	case 74:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.MergeBranchStmt{SourceBranch: yyDollar[3].str, TargetBranch: "main"}
		}
	case 75:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.DropBranchStmt{BranchName: yyDollar[3].str}
		}
	case 76:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.nodes = []ast.Node{yyDollar[1].node}
		}
	case 77:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.nodes = append(yyDollar[1].nodes, yyDollar[3].node)
		}
	case 78:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = &ast.A_Const{Type: ast.ConstInt, Val: yyDollar[1].str}
		}
	case 79:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = &ast.A_Const{Type: ast.ConstFloat, Val: yyDollar[1].str}
		}
	case 80:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = &ast.A_Const{Type: ast.ConstString, Val: yyDollar[1].str}
		}
	case 81:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = &ast.A_Const{Type: ast.ConstBool, Val: "true"}
		}
	case 82:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = &ast.A_Const{Type: ast.ConstBool, Val: "false"}
		}
	case 83:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = &ast.A_Const{Type: ast.ConstNull}
		}
	case 84:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = &ast.ParamRef{Number: yyDollar[1].ival}
		}
	case 85:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.node = colRefFromRangeVar(yyDollar[1].rangeVar)
		}
	case 86:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.FuncCall{FuncName: []string{yyDollar[1].str}}
		}
	case 87:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = &ast.FuncCall{FuncName: []string{yyDollar[1].str}, AggStar: true}
		}
	case 88:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = &ast.FuncCall{FuncName: []string{yyDollar[1].str}, Args: yyDollar[3].nodes}
		}
	case 89:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = yyDollar[2].node
		}
	case 90:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.A_Expr{Kind: ast.AEXPR_OP, Name: yyDollar[2].str, Lexpr: yyDollar[1].node, Rexpr: yyDollar[3].node}
		}
	case 91:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.A_Expr{Kind: ast.AEXPR_OP, Name: yyDollar[2].str, Lexpr: yyDollar[1].node, Rexpr: yyDollar[3].node}
		}
	case 92:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.A_Expr{Kind: ast.AEXPR_OP, Name: yyDollar[2].str, Lexpr: yyDollar[1].node, Rexpr: yyDollar[3].node}
		}
	case 93:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.A_Expr{Kind: ast.AEXPR_OP, Name: "*", Lexpr: yyDollar[1].node, Rexpr: yyDollar[3].node}
		}
	case 94:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.A_Expr{Kind: ast.AEXPR_OP, Name: yyDollar[2].str, Lexpr: yyDollar[1].node, Rexpr: yyDollar[3].node}
		}
	case 95:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.A_Expr{Kind: ast.AEXPR_OP, Name: yyDollar[2].str, Lexpr: yyDollar[1].node, Rexpr: yyDollar[3].node}
		}
	case 96:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.BoolExpr{Op: ast.AND_EXPR, Args: []ast.Node{yyDollar[1].node, yyDollar[3].node}}
		}
	case 97:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.BoolExpr{Op: ast.OR_EXPR, Args: []ast.Node{yyDollar[1].node, yyDollar[3].node}}
		}
	case 98:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.node = &ast.BoolExpr{Op: ast.NOT_EXPR, Args: []ast.Node{yyDollar[2].node}}
		}
	case 99:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.NullTest{Arg: yyDollar[1].node, TestNull: true}
		}
	case 100:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.node = &ast.NullTest{Arg: yyDollar[1].node, TestNull: false}
		}
	case 101:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.node = &ast.TypeCast{Arg: yyDollar[1].node, TypeName: yyDollar[3].str}
		}
	case 102:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.node = &ast.A_Expr{Kind: ast.AEXPR_OP, Name: yyDollar[1].str, Rexpr: yyDollar[2].node}
		}
	case 103:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.rangeVar = &ast.RangeVar{RelName: yyDollar[1].str}
		}
	case 104:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.rangeVar = &ast.RangeVar{SchemaName: yyDollar[1].str, RelName: yyDollar[3].str}
		}
	case 105:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.strs = []string{yyDollar[1].str}
		}
	case 106:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.strs = append(yyDollar[1].strs, yyDollar[3].str)
		}
	}
	goto yystack /* stack new state and value */
}
