// Code generated by goyacc -o internal/parser/sql.go -v internal/parser/y.output internal/parser/sql.y. DO NOT EDIT.

//line internal/parser/sql.y:1

// Code generated by goyacc. DO NOT EDIT manually.
// Source grammar: sql.y (milestone-1, ADR-008). Emits engine/internal/ast.
package parser

import __yyfmt__ "fmt"

//line internal/parser/sql.y:5

import "github.com/cloudtasticdev/basuyudb/engine/internal/ast"

//line internal/parser/sql.y:9
type yySymType struct {
	yys        int
	str        string
	ival       int
	node       ast.Node
	nodes      []ast.Node
	resTargets []*ast.ResTarget
	resTarget  *ast.ResTarget
	rangeVar   *ast.RangeVar
	sortList   []*ast.SortBy
	sortBy     *ast.SortBy
	strs       []string
	colDefs    []ast.ColumnDef
	colDef     ast.ColumnDef
	colQual    ast.ColQual
	colQuals   []ast.ColQual
	caseWhen   *ast.CaseWhen
	caseWhens  []*ast.CaseWhen
	withClause *ast.WithClause
	cte        *ast.CommonTableExpr
	ctes       []*ast.CommonTableExpr
	windowDef  *ast.WindowDef
	copyStmt   *ast.CopyStmt
	jt         ast.JoinType
	boolVal    bool
	onConflict *ast.OnConflictClause
}

const IDENT = 57346
const SCONST = 57347
const ICONST = 57348
const FCONST = 57349
const OP = 57350
const COMPARE_OP = 57351
const ADD_OP = 57352
const MUL_OP = 57353
const JSON_OP = 57354
const VECTOR_OP = 57355
const STAR = 57356
const PARAM = 57357
const SELECT = 57358
const FROM = 57359
const WHERE = 57360
const AS = 57361
const JOIN = 57362
const INNER = 57363
const LEFT = 57364
const RIGHT = 57365
const FULL = 57366
const CROSS = 57367
const ON = 57368
const USING = 57369
const AND = 57370
const OR = 57371
const NOT = 57372
const NULL = 57373
const IS = 57374
const ORDER = 57375
const BY = 57376
const ASC = 57377
const DESC = 57378
const GROUP = 57379
const HAVING = 57380
const LIMIT = 57381
const OFFSET = 57382
const INSERT = 57383
const INTO = 57384
const VALUES = 57385
const UPDATE = 57386
const SET = 57387
const DELETE = 57388
const CREATE = 57389
const TABLE = 57390
const PRIMARY = 57391
const KEY = 57392
const INDEX = 57393
const UNIQUE = 57394
const BRANCH = 57395
const MERGE = 57396
const DROP = 57397
const TRUE = 57398
const FALSE = 57399
const DISTINCT = 57400
const TYPECAST = 57401
const ALTER = 57402
const TRUNCATE = 57403
const COLUMN = 57404
const ADD = 57405
const IF = 57406
const EXISTS = 57407
const IN = 57408
const RETURNING = 57409
const CONFLICT = 57410
const DO = 57411
const NOTHING = 57412
const DEFAULT = 57413
const CASE = 57414
const WHEN = 57415
const THEN = 57416
const ELSE = 57417
const END = 57418
const UNION = 57419
const INTERSECT = 57420
const EXCEPT = 57421
const ALL = 57422
const REFERENCES = 57423
const CHECK = 57424
const FOREIGN = 57425
const WITH = 57426
const OVER = 57427
const PARTITION = 57428
const VIEW = 57429
const REPLACE = 57430
const COPY = 57431
const TO = 57432
const STDIN = 57433
const STDOUT = 57434
const FORMAT = 57435
const DELIMITER = 57436
const HEADER = 57437
const UMINUS = 57438
const COLDEFAULT = 57439

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"IDENT",
	"SCONST",
	"ICONST",
	"FCONST",
	"OP",
	"COMPARE_OP",
	"ADD_OP",
	"MUL_OP",
	"JSON_OP",
	"VECTOR_OP",
	"STAR",
	"PARAM",
	"SELECT",
	"FROM",
	"WHERE",
	"AS",
	"JOIN",
	"INNER",
	"LEFT",
	"RIGHT",
	"FULL",
	"CROSS",
	"ON",
	"USING",
	"AND",
	"OR",
	"NOT",
	"NULL",
	"IS",
	"ORDER",
	"BY",
	"ASC",
	"DESC",
	"GROUP",
	"HAVING",
	"LIMIT",
	"OFFSET",
	"INSERT",
	"INTO",
	"VALUES",
	"UPDATE",
	"SET",
	"DELETE",
	"CREATE",
	"TABLE",
	"PRIMARY",
	"KEY",
	"INDEX",
	"UNIQUE",
	"BRANCH",
	"MERGE",
	"DROP",
	"TRUE",
	"FALSE",
	"DISTINCT",
	"TYPECAST",
	"ALTER",
	"TRUNCATE",
	"COLUMN",
	"ADD",
	"IF",
	"EXISTS",
	"IN",
	"RETURNING",
	"CONFLICT",
	"DO",
	"NOTHING",
	"DEFAULT",
	"CASE",
	"WHEN",
	"THEN",
	"ELSE",
	"END",
	"UNION",
	"INTERSECT",
	"EXCEPT",
	"ALL",
	"REFERENCES",
	"CHECK",
	"FOREIGN",
	"WITH",
	"OVER",
	"PARTITION",
	"VIEW",
	"REPLACE",
	"COPY",
	"TO",
	"STDIN",
	"STDOUT",
	"FORMAT",
	"DELIMITER",
	"HEADER",
	"UMINUS",
	"COLDEFAULT",
	"';'",
	"','",
	"'('",
	"')'",
	"'.'",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line internal/parser/sql.y:652

//line yacctab:1
var yyExca = [...]int16{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 204,
	20, 49,
	-2, 43,
	-1, 304,
	20, 49,
	-2, 44,
}

const yyPrivate = 57344

const yyLast = 582

var yyAct = [...]int16{
	111, 225, 130, 224, 173, 332, 53, 205, 344, 279,
	285, 204, 247, 229, 3, 142, 177, 91, 112, 102,
	115, 92, 161, 194, 62, 390, 103, 97, 95, 96,
	62, 194, 107, 389, 385, 294, 223, 101, 32, 359,
	384, 358, 44, 381, 194, 48, 357, 356, 343, 355,
	342, 60, 106, 100, 63, 64, 65, 272, 380, 341,
	94, 70, 72, 378, 80, 75, 76, 194, 365, 329,
	156, 155, 153, 151, 152, 154, 340, 308, 98, 99,
	156, 155, 153, 151, 152, 154, 137, 271, 252, 157,
	158, 150, 143, 159, 108, 321, 272, 320, 309, 157,
	158, 150, 272, 159, 273, 238, 162, 237, 164, 165,
	167, 227, 194, 169, 232, 295, 132, 382, 175, 163,
	160, 33, 104, 222, 194, 146, 193, 149, 377, 353,
	160, 293, 170, 179, 348, 347, 327, 149, 197, 180,
	181, 313, 187, 184, 185, 299, 298, 94, 383, 196,
	269, 267, 243, 210, 211, 212, 213, 214, 215, 216,
	217, 171, 373, 231, 208, 201, 206, 202, 116, 134,
	117, 272, 226, 110, 235, 233, 94, 79, 145, 256,
	198, 81, 28, 103, 97, 95, 96, 251, 192, 107,
	234, 29, 236, 191, 101, 103, 97, 95, 96, 195,
	143, 107, 244, 245, 66, 249, 101, 145, 119, 106,
	100, 316, 266, 346, 253, 128, 314, 49, 333, 334,
	335, 106, 100, 265, 17, 270, 41, 18, 248, 19,
	20, 43, 277, 280, 87, 98, 99, 24, 21, 26,
	55, 317, 275, 23, 22, 230, 297, 98, 99, 171,
	281, 108, 57, 174, 387, 282, 86, 296, 230, 391,
	276, 393, 51, 108, 300, 42, 209, 26, 304, 371,
	124, 311, 25, 123, 315, 26, 206, 138, 318, 104,
	139, 140, 310, 103, 97, 95, 96, 392, 129, 107,
	160, 104, 325, 93, 101, 322, 54, 55, 56, 59,
	33, 330, 47, 33, 336, 68, 151, 337, 189, 106,
	100, 326, 126, 338, 339, 37, 103, 97, 95, 96,
	125, 349, 107, 280, 178, 206, 206, 101, 324, 354,
	33, 352, 85, 46, 35, 98, 99, 38, 39, 40,
	286, 287, 106, 100, 133, 155, 153, 151, 152, 154,
	394, 108, 366, 160, 61, 370, 368, 369, 168, 288,
	73, 127, 289, 71, 376, 375, 188, 31, 98, 99,
	136, 379, 84, 36, 45, 302, 255, 367, 303, 104,
	386, 290, 186, 90, 108, 57, 388, 323, 88, 89,
	268, 291, 292, 351, 160, 395, 156, 155, 153, 151,
	152, 154, 156, 155, 153, 151, 152, 154, 219, 218,
	362, 363, 104, 242, 182, 157, 158, 150, 120, 159,
	306, 157, 158, 150, 305, 159, 118, 82, 199, 200,
	148, 116, 263, 122, 34, 156, 155, 153, 151, 152,
	154, 153, 151, 30, 154, 147, 160, 264, 172, 374,
	364, 328, 160, 149, 157, 158, 150, 312, 159, 149,
	361, 319, 113, 156, 155, 153, 151, 152, 154, 131,
	372, 156, 155, 153, 151, 152, 154, 155, 153, 151,
	360, 154, 157, 158, 150, 160, 159, 33, 307, 160,
	157, 158, 149, 178, 159, 156, 155, 153, 151, 152,
	154, 156, 155, 153, 151, 152, 154, 250, 259, 260,
	261, 262, 258, 160, 157, 246, 150, 241, 159, 221,
	149, 160, 150, 207, 159, 190, 160, 183, 149, 52,
	121, 114, 77, 74, 69, 67, 27, 1, 58, 257,
	220, 240, 239, 78, 331, 160, 345, 50, 16, 228,
	274, 160, 149, 166, 105, 283, 284, 176, 149, 109,
	141, 350, 278, 254, 203, 144, 135, 83, 301, 14,
	13, 12, 11, 10, 9, 15, 8, 7, 6, 5,
	4, 2,
}

var yyPact = [...]int16{
	183, -1000, 84, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, 427, 325, 483, 417,
	286, 178, 326, 285, 249, 117, 525, -1000, -1000, 219,
	241, 483, 309, -72, 483, 483, 483, 116, 531, 254,
	530, 299, 296, 529, -1000, 483, 483, 528, 77, 155,
	82, -1000, 408, 333, 176, 176, 176, 349, 279, -1000,
	73, 458, 527, 413, 70, 407, 121, 392, 526, 416,
	-1000, 208, -1000, 205, -1000, -1000, 257, 319, 198, 465,
	15, 525, 69, 330, 312, 427, -1000, -1000, 427, 427,
	312, 108, -1000, -1000, 426, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -78, 191, -1000, 312, 312, 312, 315,
	465, 150, -1000, 439, -1000, 186, 312, 489, 155, 483,
	483, 388, 523, 483, 483, 320, 304, 521, 102, 96,
	25, -1000, 109, -1000, 155, -1000, 312, 454, 162, -1000,
	162, 81, -1000, 393, 413, 279, 483, 519, -1000, 64,
	200, 312, 312, 312, 312, 312, 312, 312, 312, 378,
	515, 22, 71, 10, 492, -1000, 172, 454, 63, 13,
	186, 458, 312, -1000, 279, 454, 6, -1000, 513, -1000,
	394, 52, 483, -1000, -1000, -1000, 489, -1000, 511, -1000,
	-1000, 144, 144, -1000, 503, 95, -13, 454, 312, -1000,
	-1000, 339, -1000, 80, 487, -1000, 428, -1000, 191, 51,
	231, 467, 294, 294, 430, 335, 492, 486, -1000, 359,
	-1000, 50, 140, -14, 3, 454, -1000, -1000, 185, -1000,
	312, 179, -1000, -1000, -1000, 454, 79, -1000, 489, 310,
	31, -1000, 155, 465, 46, -1000, -1000, -1000, 45, -1000,
	-1000, 144, -1000, -1000, 337, 344, 483, 404, 400, -1000,
	-1000, -1000, -1000, -1000, 484, -24, -3, 191, -1000, 451,
	41, 131, 312, 126, 165, -1000, 312, 387, -4, -1000,
	454, -1000, -1000, -1000, 310, -1000, 356, -1000, 278, -1000,
	312, 483, 36, 445, -1000, -1000, -1000, -32, 465, 125,
	-1000, -1000, 312, 312, 487, 483, 483, -1000, -1000, -1000,
	-25, -42, -51, 127, 35, 454, 34, -1000, 454, 312,
	367, 179, -1000, -1000, -1000, 462, 29, 312, -52, -1000,
	-55, -60, -1000, 476, 455, -1000, 454, 72, 384, -1000,
	-1000, -1000, -1000, 444, -33, 352, 343, 127, 127, 454,
	186, 201, -1000, 466, 61, -1000, 443, -1000, -1000, 125,
	-1000, -1000, 312, 28, -38, -1000, -1000, 312, -43, -58,
	-1000, 48, -61, -1000, -67, -1000, 454, 465, -1000, 72,
	-1000, -1000, 184, 465, -1000, -1000, -68, -1000, -76, -1000,
	190, 217, -1000, 305, 458, 62,
}

var yyPgo = [...]int16{
	0, 581, 14, 191, 580, 579, 578, 577, 576, 575,
	574, 573, 572, 571, 570, 569, 1, 7, 11, 20,
	568, 567, 566, 565, 564, 3, 563, 562, 9, 17,
	0, 4, 561, 21, 18, 19, 6, 560, 15, 2,
	559, 557, 16, 10, 556, 555, 554, 553, 550, 13,
	549, 548, 262, 547, 8, 546, 12, 544, 5, 543,
	542, 541, 540, 539, 538, 332, 537, 536,
}

var yyR1 = [...]int8{
	0, 66, 67, 67, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 2, 51, 51,
	53, 53, 52, 54, 55, 55, 3, 3, 3, 3,
	65, 65, 65, 64, 64, 29, 29, 33, 33, 33,
	33, 23, 23, 24, 24, 18, 18, 18, 18, 63,
	63, 63, 63, 63, 17, 17, 17, 19, 19, 26,
	26, 20, 20, 36, 36, 37, 37, 38, 38, 38,
	21, 21, 22, 22, 4, 27, 27, 28, 28, 40,
	40, 32, 32, 32, 32, 31, 31, 5, 30, 30,
	34, 6, 7, 7, 7, 8, 8, 10, 10, 10,
	10, 9, 9, 9, 59, 59, 56, 56, 57, 57,
	58, 58, 58, 11, 11, 12, 12, 12, 12, 41,
	41, 42, 45, 45, 44, 44, 43, 43, 43, 43,
	43, 43, 43, 43, 60, 60, 60, 61, 61, 61,
	62, 62, 62, 13, 13, 14, 14, 15, 25, 25,
	16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
	16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
	16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
	16, 16, 16, 16, 46, 47, 47, 50, 50, 49,
	48, 48, 35, 35, 39, 39,
}

var yyR2 = [...]int8{
	0, 2, 0, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 5, 0, 2,
	1, 3, 5, 2, 0, 3, 7, 4, 4, 4,
	0, 1, 1, 0, 1, 1, 3, 1, 1, 3,
	2, 0, 2, 1, 3, 1, 6, 8, 4, 0,
	1, 1, 1, 1, 1, 2, 3, 0, 2, 0,
	3, 0, 2, 0, 3, 1, 3, 1, 2, 2,
	0, 2, 0, 2, 10, 1, 3, 1, 1, 0,
	3, 0, 4, 7, 9, 0, 2, 6, 1, 3,
	3, 5, 6, 5, 7, 8, 9, 3, 5, 3,
	5, 6, 6, 7, 0, 3, 0, 4, 1, 3,
	2, 2, 1, 2, 3, 6, 5, 6, 5, 1,
	3, 3, 0, 1, 1, 2, 2, 1, 2, 1,
	2, 2, 5, 4, 1, 4, 6, 1, 2, 2,
	1, 4, 6, 3, 5, 5, 3, 3, 1, 3,
	1, 1, 1, 1, 1, 1, 1, 1, 3, 4,
	4, 7, 8, 8, 3, 1, 3, 5, 5, 6,
	6, 3, 3, 3, 3, 3, 3, 3, 3, 2,
	3, 4, 3, 2, 5, 0, 1, 1, 2, 4,
	0, 2, 1, 3, 1, 3,
}

var yyChk = [...]int16{
	-1000, -66, -1, -2, -4, -5, -6, -7, -8, -10,
	-11, -12, -13, -14, -15, -9, -51, 41, 44, 46,
	47, 55, 61, 60, 54, 89, 84, -67, 98, -3,
	16, 42, -35, 4, 17, 48, 87, 29, 51, 52,
	53, 48, 87, 53, -35, 48, 48, 53, -35, 100,
	-53, -52, 4, -36, 77, 78, 79, 33, -64, 58,
	-35, 45, 102, -35, -35, -35, 88, 4, 51, 4,
	-35, 64, -35, 64, 4, -35, -35, 4, -59, 100,
	-2, 99, 19, -21, 39, -65, 80, 58, -65, -65,
	34, -29, -33, 14, -16, 6, 7, 5, 56, 57,
	31, 15, -35, 4, 100, -46, 30, 10, 72, -40,
	100, -30, -34, 4, 4, -19, 18, 100, 19, 87,
	26, 4, 17, 65, 65, 63, 55, 42, 17, 90,
	-39, 4, 101, -52, 100, -22, 40, -16, -3, -3,
	-3, -37, -38, -16, -23, 99, 17, 19, 4, 66,
	30, 12, 13, 11, 14, 10, 9, 28, 29, 32,
	59, 100, -16, -2, -16, -16, -47, -16, 43, -39,
	-19, 99, 9, -31, 67, -16, -41, -42, 4, -2,
	-35, -35, 26, 4, -35, -35, 62, -42, 62, 4,
	4, 91, 92, 101, 99, 90, -2, -16, 99, 35,
	36, -19, -33, -24, -18, -17, -35, 4, 100, 66,
	-16, -16, -16, -16, -16, -16, -16, -16, 31, 30,
	-62, 4, 101, 14, -25, -16, 101, 101, -50, -49,
	73, 100, 101, -31, -34, -16, -29, 101, 99, -60,
	-61, 4, 19, 100, -35, -42, 4, -56, 84, -56,
	4, 92, 101, -38, -26, 37, 99, -63, 25, 21,
	22, 23, 24, 4, 19, -2, -25, 100, 31, 100,
	85, 101, 99, 101, -48, -49, 75, -16, -27, -28,
	-16, 71, -42, -45, -44, -43, 30, 31, 49, 52,
	71, 81, 82, 100, 4, 84, -2, -39, 100, 100,
	-56, -20, 38, 34, -18, 20, 20, 4, 101, 101,
	-2, -25, 6, 100, 85, -16, 85, 76, -16, 74,
	101, 99, -43, 31, 50, -16, -35, 100, 6, 101,
	-39, -57, -58, 93, 94, 95, -16, -25, -17, -17,
	101, 101, 101, 99, -54, -55, 86, 100, 100, -16,
	-32, 26, -28, 100, -16, 101, 99, 101, 101, 99,
	4, 5, 26, 27, 6, 101, -36, 34, -54, -54,
	-31, 68, 4, 101, 6, -58, -16, 100, 101, -25,
	101, 101, 69, 100, 101, 101, -39, 70, -39, 101,
	101, 69, 70, 44, 45, -30,
}

var yyDef = [...]int16{
	18, -2, 2, 4, 5, 6, 7, 8, 9, 10,
	11, 12, 13, 14, 15, 16, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 1, 3, 63,
	33, 0, 0, 192, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 113, 0, 0, 0, 104, 18,
	19, 20, 0, 70, 30, 30, 30, 0, 0, 34,
	79, 0, 0, 57, 0, 0, 0, 0, 0, 143,
	97, 0, 99, 0, 147, 114, 0, 146, 0, 0,
	0, 0, 0, 72, 0, 0, 31, 32, 0, 0,
	0, 41, 35, 37, 38, 150, 151, 152, 153, 154,
	155, 156, 157, 192, 18, 165, 0, 0, 185, 0,
	0, 57, 88, 0, 193, 85, 0, 0, 18, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 194, 0, 21, 18, 17, 0, 71, 27, 28,
	29, 64, 65, 67, 57, 0, 0, 0, 40, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 179, 183, 0, 186, 0, 0,
	85, 0, 0, 91, 0, 58, 0, 119, 0, 93,
	0, 0, 0, 144, 98, 100, 0, 116, 0, 118,
	145, 106, 106, 105, 0, 0, 0, 73, 0, 68,
	69, 59, 36, 42, -2, 45, 54, 39, 18, 0,
	171, 172, 173, 174, 175, 176, 177, 178, 180, 0,
	182, 140, 158, 0, 0, 148, 164, 166, 190, 187,
	0, 0, 80, 87, 89, 90, 86, 92, 0, 122,
	134, 137, 18, 0, 0, 115, 117, 101, 0, 102,
	195, 106, 22, 66, 61, 0, 0, 0, 0, 50,
	51, 52, 53, 55, 0, 0, 0, 18, 181, 0,
	0, 159, 0, 160, 0, 188, 0, 0, 0, 75,
	77, 78, 120, 121, 123, 124, 0, 127, 0, 129,
	0, 0, 0, 0, 138, 139, 94, 0, 0, 0,
	103, 26, 0, 0, -2, 0, 0, 56, 167, 168,
	0, 0, 0, 24, 0, 149, 0, 184, 191, 0,
	81, 0, 125, 126, 128, 130, 131, 0, 0, 95,
	0, 0, 108, 0, 0, 112, 62, 60, 0, 48,
	169, 170, 141, 0, 0, 63, 0, 24, 24, 189,
	85, 0, 76, 0, 0, 135, 0, 96, 107, 0,
	110, 111, 0, 0, 0, 161, 23, 0, 0, 0,
	74, 0, 0, 133, 0, 109, 46, 0, 142, 25,
	162, 163, 0, 0, 132, 136, 0, 82, 0, 47,
	0, 0, 83, 0, 0, 84,
}

var yyTok1 = [...]int8{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	100, 101, 3, 3, 99, 3, 102, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 98,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
	52, 53, 54, 55, 56, 57, 58, 59, 60, 61,
	62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
	72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
	82, 83, 84, 85, 86, 87, 88, 89, 90, 91,
	92, 93, 94, 95, 96, 97,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-2 : yypt+1]
//line internal/parser/sql.y:104
		{
			yylex.(*lexer).result = yyDollar[1].node
		}
	case 2:
		yyDollar = yyS[yypt-0 : yypt+1]
//line internal/parser/sql.y:109
		{
		}
	case 3:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internal/parser/sql.y:111
		{
		}
	case 4:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internal/parser/sql.y:114
		{
			yyVAL.node = yyDollar[1].node
		}
	case 5:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internal/parser/sql.y:115
		{
			yyVAL.node = yyDollar[1].node
		}
	case 6:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internal/parser/sql.y:116
		{
			yyVAL.node = yyDollar[1].node
		}
	case 7:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internal/parser/sql.y:117
		{
			yyVAL.node = yyDollar[1].node
		}
	case 8:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internal/parser/sql.y:118
		{
			yyVAL.node = yyDollar[1].node
		}
	case 9:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internal/parser/sql.y:119
		{
			yyVAL.node = yyDollar[1].node
		}
	case 10:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internal/parser/sql.y:120
		{
			yyVAL.node = yyDollar[1].node
		}
	case 11:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internal/parser/sql.y:121
		{
			yyVAL.node = yyDollar[1].node
		}
	case 12:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internal/parser/sql.y:122
		{
			yyVAL.node = yyDollar[1].node
		}
	case 13:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internal/parser/sql.y:123
		{
			yyVAL.node = yyDollar[1].node
		}
	case 14:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internal/parser/sql.y:124
		{
			yyVAL.node = yyDollar[1].node
		}
	case 15:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internal/parser/sql.y:125
		{
			yyVAL.node = yyDollar[1].node
		}
	case 16:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internal/parser/sql.y:126
		{
			yyVAL.node = yyDollar[1].node
		}
	case 17:
		yyDollar = yyS[yypt-5 : yypt+1]
//line internal/parser/sql.y:133
		{
			sel := yyDollar[2].node.(*ast.SelectStmt)
			sel.WithClause = yyDollar[1].withClause
			sel.SortClause = yyDollar[3].sortList
			sel.LimitCount = yyDollar[4].node
			sel.LimitOffset = yyDollar[5].node
			yyVAL.node = sel
		}
	case 18:
		yyDollar = yyS[yypt-0 : yypt+1]
//line internal/parser/sql.y:143
		{
			yyVAL.withClause = nil
		}
	case 19:
		yyDollar = yyS[yypt-2 : yypt+1]
//line internal/parser/sql.y:145
		{
			yyVAL.withClause = &ast.WithClause{CTEs: yyDollar[2].ctes}
		}
	case 20:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internal/parser/sql.y:149
		{
			yyVAL.ctes = []*ast.CommonTableExpr{yyDollar[1].cte}
		}
	case 21:
		yyDollar = yyS[yypt-3 : yypt+1]
//line internal/parser/sql.y:151
		{
			yyVAL.ctes = append(yyDollar[1].ctes, yyDollar[3].cte)
		}
	case 22:
		yyDollar = yyS[yypt-5 : yypt+1]
//line internal/parser/sql.y:155
		{
			yyVAL.cte = &ast.CommonTableExpr{Name: yyDollar[1].str, Query: yyDollar[4].node}
		}
	case 23:
		yyDollar = yyS[yypt-2 : yypt+1]
//line internal/parser/sql.y:160
		{
			yyVAL.windowDef = &ast.WindowDef{PartitionBy: yyDollar[1].nodes, OrderBy: yyDollar[2].sortList}
		}
	case 24:
		yyDollar = yyS[yypt-0 : yypt+1]
//line internal/parser/sql.y:163
		{
			yyVAL.nodes = nil
		}
	case 25:
		yyDollar = yyS[yypt-3 : yypt+1]
//line internal/parser/sql.y:165
		{
			yyVAL.nodes = yyDollar[3].nodes
		}
	case 26:
		yyDollar = yyS[yypt-7 : yypt+1]
//line internal/parser/sql.y:169
		{
			yyVAL.node = &ast.SelectStmt{
				Distinct:     yyDollar[2].boolVal,
				TargetList:   yyDollar[3].resTargets,
				FromClause:   yyDollar[4].nodes,
				WhereClause:  yyDollar[5].node,
				GroupClause:  yyDollar[6].nodes,
				HavingClause: yyDollar[7].node,
			}
		}
	case 27:
		yyDollar = yyS[yypt-4 : yypt+1]
//line internal/parser/sql.y:180
		{
			yyVAL.node = &ast.SelectStmt{SetOp: ast.SetOpUnion, All: yyDollar[3].boolVal, Larg: yyDollar[1].node.(*ast.SelectStmt), Rarg: yyDollar[4].node.(*ast.SelectStmt)}
		}
	case 28:
		yyDollar = yyS[yypt-4 : yypt+1]
//line internal/parser/sql.y:182
		{
			yyVAL.node = &ast.SelectStmt{SetOp: ast.SetOpIntersect, All: yyDollar[3].boolVal, Larg: yyDollar[1].node.(*ast.SelectStmt), Rarg: yyDollar[4].node.(*ast.SelectStmt)}
		}
	case 29:
		yyDollar = yyS[yypt-4 : yypt+1]
//line internal/parser/sql.y:184
		{
			yyVAL.node = &ast.SelectStmt{SetOp: ast.SetOpExcept, All: yyDollar[3].boolVal, Larg: yyDollar[1].node.(*ast.SelectStmt), Rarg: yyDollar[4].node.(*ast.SelectStmt)}
		}
	case 30:
		yyDollar = yyS[yypt-0 : yypt+1]
//line internal/parser/sql.y:187
		{
			yyVAL.boolVal = false
		}
	case 31:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internal/parser/sql.y:189
		{
			yyVAL.boolVal = true
		}
	case 32:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internal/parser/sql.y:191
		{
			yyVAL.boolVal = false
		}
	case 33:
		yyDollar = yyS[yypt-0 : yypt+1]
//line internal/parser/sql.y:194
		{
			yyVAL.boolVal = false
		}
	case 34:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internal/parser/sql.y:196
		{
			yyVAL.boolVal = true
		}
	case 35:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internal/parser/sql.y:200
		{
			yyVAL.resTargets = []*ast.ResTarget{yyDollar[1].resTarget}
		}
	case 36:
		yyDollar = yyS[yypt-3 : yypt+1]
//line internal/parser/sql.y:202
		{
			yyVAL.resTargets = append(yyDollar[1].resTargets, yyDollar[3].resTarget)
		}
	case 37:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internal/parser/sql.y:206
		{
			yyVAL.resTarget = &ast.ResTarget{Val: &ast.A_Star{}}
		}
	case 38:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internal/parser/sql.y:208
		{
			yyVAL.resTarget = &ast.ResTarget{Val: yyDollar[1].node}
		}
	case 39:
		yyDollar = yyS[yypt-3 : yypt+1]
//line internal/parser/sql.y:210
		{
			yyVAL.resTarget = &ast.ResTarget{Name: yyDollar[3].str, Val: yyDollar[1].node}
		}
	case 40:
		yyDollar = yyS[yypt-2 : yypt+1]
//line internal/parser/sql.y:212
		{
			yyVAL.resTarget = &ast.ResTarget{Name: yyDollar[2].str, Val: yyDollar[1].node}
		}
	case 41:
		yyDollar = yyS[yypt-0 : yypt+1]
//line internal/parser/sql.y:215
		{
			yyVAL.nodes = nil
		}
	case 42:
		yyDollar = yyS[yypt-2 : yypt+1]
//line internal/parser/sql.y:217
		{
			yyVAL.nodes = yyDollar[2].nodes
		}
	case 43:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internal/parser/sql.y:221
		{
			yyVAL.nodes = []ast.Node{yyDollar[1].node}
		}
	case 44:
		yyDollar = yyS[yypt-3 : yypt+1]
//line internal/parser/sql.y:223
		{
			yyVAL.nodes = append(yyDollar[1].nodes, yyDollar[3].node)
		}
	case 45:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internal/parser/sql.y:227
		{
			yyVAL.node = yyDollar[1].node
		}
	case 46:
		yyDollar = yyS[yypt-6 : yypt+1]
//line internal/parser/sql.y:229
		{
			yyVAL.node = &ast.JoinExpr{JoinType: yyDollar[2].jt, Larg: yyDollar[1].node, Rarg: yyDollar[4].node, Quals: yyDollar[6].node}
		}
	case 47:
		yyDollar = yyS[yypt-8 : yypt+1]
//line internal/parser/sql.y:231
		{
			yyVAL.node = &ast.JoinExpr{JoinType: yyDollar[2].jt, Larg: yyDollar[1].node, Rarg: yyDollar[4].node, UsingCols: yyDollar[7].strs}
		}
	case 48:
		yyDollar = yyS[yypt-4 : yypt+1]
//line internal/parser/sql.y:233
		{
			yyVAL.node = &ast.JoinExpr{JoinType: ast.JOIN_CROSS, Larg: yyDollar[1].node, Rarg: yyDollar[4].node}
		}
	case 49:
		yyDollar = yyS[yypt-0 : yypt+1]
//line internal/parser/sql.y:236
		{
			yyVAL.jt = ast.JOIN_INNER
		}
	case 50:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internal/parser/sql.y:238
		{
			yyVAL.jt = ast.JOIN_INNER
		}
	case 51:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internal/parser/sql.y:240
		{
			yyVAL.jt = ast.JOIN_LEFT
		}
	case 52:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internal/parser/sql.y:242
		{
			yyVAL.jt = ast.JOIN_RIGHT
		}
	case 53:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internal/parser/sql.y:244
		{
			yyVAL.jt = ast.JOIN_FULL
		}
	case 54:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internal/parser/sql.y:248
		{
			yyVAL.node = yyDollar[1].rangeVar
		}
	case 55:
		yyDollar = yyS[yypt-2 : yypt+1]
//line internal/parser/sql.y:250
		{
			yyDollar[1].rangeVar.Alias = &ast.Alias{AliasName: yyDollar[2].str}
			yyVAL.node = yyDollar[1].rangeVar
		}
	case 56:
		yyDollar = yyS[yypt-3 : yypt+1]
//line internal/parser/sql.y:252
		{
			yyDollar[1].rangeVar.Alias = &ast.Alias{AliasName: yyDollar[3].str}
			yyVAL.node = yyDollar[1].rangeVar
		}
	case 57:
		yyDollar = yyS[yypt-0 : yypt+1]
//line internal/parser/sql.y:255
		{
			yyVAL.node = nil
		}
	case 58:
		yyDollar = yyS[yypt-2 : yypt+1]
//line internal/parser/sql.y:257
		{
			yyVAL.node = yyDollar[2].node
		}
	case 59:
		yyDollar = yyS[yypt-0 : yypt+1]
//line internal/parser/sql.y:260
		{
			yyVAL.nodes = nil
		}
	case 60:
		yyDollar = yyS[yypt-3 : yypt+1]
//line internal/parser/sql.y:262
		{
			yyVAL.nodes = yyDollar[3].nodes
		}
	case 61:
		yyDollar = yyS[yypt-0 : yypt+1]
//line internal/parser/sql.y:265
		{
			yyVAL.node = nil
		}
	case 62:
		yyDollar = yyS[yypt-2 : yypt+1]
//line internal/parser/sql.y:267
		{
			yyVAL.node = yyDollar[2].node
		}
	case 63:
		yyDollar = yyS[yypt-0 : yypt+1]
//line internal/parser/sql.y:270
		{
			yyVAL.sortList = nil
		}
	case 64:
		yyDollar = yyS[yypt-3 : yypt+1]
//line internal/parser/sql.y:272
		{
			yyVAL.sortList = yyDollar[3].sortList
		}
	case 65:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internal/parser/sql.y:276
		{
			yyVAL.sortList = []*ast.SortBy{yyDollar[1].sortBy}
		}
	case 66:
		yyDollar = yyS[yypt-3 : yypt+1]
//line internal/parser/sql.y:278
		{
			yyVAL.sortList = append(yyDollar[1].sortList, yyDollar[3].sortBy)
		}
	case 67:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internal/parser/sql.y:282
		{
			yyVAL.sortBy = &ast.SortBy{Node: yyDollar[1].node, SortDir: 0}
		}
	case 68:
		yyDollar = yyS[yypt-2 : yypt+1]
//line internal/parser/sql.y:284
		{
			yyVAL.sortBy = &ast.SortBy{Node: yyDollar[1].node, SortDir: 1}
		}
	case 69:
		yyDollar = yyS[yypt-2 : yypt+1]
//line internal/parser/sql.y:286
		{
			yyVAL.sortBy = &ast.SortBy{Node: yyDollar[1].node, SortDir: 2}
		}
	case 70:
		yyDollar = yyS[yypt-0 : yypt+1]
//line internal/parser/sql.y:289
		{
			yyVAL.node = nil
		}
	case 71:
		yyDollar = yyS[yypt-2 : yypt+1]
//line internal/parser/sql.y:291
		{
			yyVAL.node = yyDollar[2].node
		}
	case 72:
		yyDollar = yyS[yypt-0 : yypt+1]
//line internal/parser/sql.y:294
		{
			yyVAL.node = nil
		}
	case 73:
		yyDollar = yyS[yypt-2 : yypt+1]
//line internal/parser/sql.y:296
		{
			yyVAL.node = yyDollar[2].node
		}
	case 74:
		yyDollar = yyS[yypt-10 : yypt+1]
//line internal/parser/sql.y:301
		{
			cols := make([]*ast.ResTarget, 0, len(yyDollar[4].strs))
			for _, c := range yyDollar[4].strs {
				cols = append(cols, &ast.ResTarget{Name: c})
			}
			yyVAL.node = &ast.InsertStmt{
				Relation:      yyDollar[3].rangeVar,
				Cols:          cols,
				SelectStmt:    &ast.SelectStmt{TargetList: valuesToTargets(yyDollar[7].nodes)},
				OnConflict:    yyDollar[9].onConflict,
				ReturningList: yyDollar[10].resTargets,
			}
		}
	case 75:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internal/parser/sql.y:319
		{
			yyVAL.nodes = []ast.Node{yyDollar[1].node}
		}
	case 76:
		yyDollar = yyS[yypt-3 : yypt+1]
//line internal/parser/sql.y:321
		{
			yyVAL.nodes = append(yyDollar[1].nodes, yyDollar[3].node)
		}
	case 77:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internal/parser/sql.y:325
		{
			yyVAL.node = yyDollar[1].node
		}
	case 78:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internal/parser/sql.y:327
		{
			yyVAL.node = &ast.SetToDefault{}
		}
	case 79:
		yyDollar = yyS[yypt-0 : yypt+1]
//line internal/parser/sql.y:330
		{
			yyVAL.strs = nil
		}
	case 80:
		yyDollar = yyS[yypt-3 : yypt+1]
//line internal/parser/sql.y:332
		{
			yyVAL.strs = yyDollar[2].strs
		}
	case 81:
		yyDollar = yyS[yypt-0 : yypt+1]
//line internal/parser/sql.y:335
		{
			yyVAL.onConflict = nil
		}
	case 82:
		yyDollar = yyS[yypt-4 : yypt+1]
//line internal/parser/sql.y:337
		{
			yyVAL.onConflict = &ast.OnConflictClause{DoNothing: true}
		}
	case 83:
		yyDollar = yyS[yypt-7 : yypt+1]
//line internal/parser/sql.y:339
		{
			yyVAL.onConflict = &ast.OnConflictClause{Columns: yyDollar[4].strs, DoNothing: true}
		}
	case 84:
		yyDollar = yyS[yypt-9 : yypt+1]
//line internal/parser/sql.y:341
		{
			yyVAL.onConflict = &ast.OnConflictClause{Columns: yyDollar[4].strs, DoUpdateSet: yyDollar[9].resTargets}
		}
	case 85:
		yyDollar = yyS[yypt-0 : yypt+1]
//line internal/parser/sql.y:344
		{
			yyVAL.resTargets = nil
		}
	case 86:
		yyDollar = yyS[yypt-2 : yypt+1]
//line internal/parser/sql.y:346
		{
			yyVAL.resTargets = yyDollar[2].resTargets
		}
	case 87:
		yyDollar = yyS[yypt-6 : yypt+1]
//line internal/parser/sql.y:351
		{
			yyVAL.node = &ast.UpdateStmt{Relation: yyDollar[2].rangeVar, TargetList: yyDollar[4].resTargets, WhereClause: yyDollar[5].node, ReturningList: yyDollar[6].resTargets}
		}
	case 88:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internal/parser/sql.y:355
		{
			yyVAL.resTargets = []*ast.ResTarget{yyDollar[1].resTarget}
		}
	case 89:
		yyDollar = yyS[yypt-3 : yypt+1]
//line internal/parser/sql.y:357
		{
			yyVAL.resTargets = append(yyDollar[1].resTargets, yyDollar[3].resTarget)
		}
	case 90:
		yyDollar = yyS[yypt-3 : yypt+1]
//line internal/parser/sql.y:361
		{
			if yyDollar[2].str != "=" {
				yylex.Error("expected = in SET assignment")
			}
			yyVAL.resTarget = &ast.ResTarget{Name: yyDollar[1].str, Val: yyDollar[3].node}
		}
	case 91:
		yyDollar = yyS[yypt-5 : yypt+1]
//line internal/parser/sql.y:369
		{
			yyVAL.node = &ast.DeleteStmt{Relation: yyDollar[3].rangeVar, WhereClause: yyDollar[4].node, ReturningList: yyDollar[5].resTargets}
		}
	case 92:
		yyDollar = yyS[yypt-6 : yypt+1]
//line internal/parser/sql.y:374
		{
			yyVAL.node = &ast.CreateStmt{Relation: yyDollar[3].rangeVar, TableElts: yyDollar[5].colDefs}
		}
	case 93:
		yyDollar = yyS[yypt-5 : yypt+1]
//line internal/parser/sql.y:376
		{
			yyVAL.node = &ast.CreateViewStmt{Relation: yyDollar[3].rangeVar, Query: yyDollar[5].node}
		}
	case 94:
		yyDollar = yyS[yypt-7 : yypt+1]
//line internal/parser/sql.y:378
		{
			yyVAL.node = &ast.CreateViewStmt{Relation: yyDollar[5].rangeVar, Query: yyDollar[7].node, Replace: true}
		}
	case 95:
		yyDollar = yyS[yypt-8 : yypt+1]
//line internal/parser/sql.y:382
		{
			yyVAL.node = &ast.IndexStmt{Name: yyDollar[3].str, Table: yyDollar[5].rangeVar.RelName, Columns: yyDollar[7].strs}
		}
	case 96:
		yyDollar = yyS[yypt-9 : yypt+1]
//line internal/parser/sql.y:384
		{
			yyVAL.node = &ast.IndexStmt{Name: yyDollar[4].str, Table: yyDollar[6].rangeVar.RelName, Columns: yyDollar[8].strs, Unique: true}
		}
	case 97:
		yyDollar = yyS[yypt-3 : yypt+1]
//line internal/parser/sql.y:388
		{
			yyVAL.node = &ast.DropStmt{Table: yyDollar[3].rangeVar.RelName}
		}
	case 98:
		yyDollar = yyS[yypt-5 : yypt+1]
//line internal/parser/sql.y:390
		{
			yyVAL.node = &ast.DropStmt{Table: yyDollar[5].rangeVar.RelName, IfExists: true}
		}
	case 99:
		yyDollar = yyS[yypt-3 : yypt+1]
//line internal/parser/sql.y:392
		{
			yyVAL.node = &ast.DropStmt{Table: yyDollar[3].rangeVar.RelName, IsView: true}
		}
	case 100:
		yyDollar = yyS[yypt-5 : yypt+1]
//line internal/parser/sql.y:394
		{
			yyVAL.node = &ast.DropStmt{Table: yyDollar[5].rangeVar.RelName, IfExists: true, IsView: true}
		}
	case 101:
		yyDollar = yyS[yypt-6 : yypt+1]
//line internal/parser/sql.y:399
		{
			c := yyDollar[6].copyStmt
			c.Table = yyDollar[2].rangeVar.RelName
			c.Columns = yyDollar[3].strs
			c.IsFrom = true
			yyVAL.node = c
		}
	case 102:
		yyDollar = yyS[yypt-6 : yypt+1]
//line internal/parser/sql.y:401
		{
			c := yyDollar[6].copyStmt
			c.Table = yyDollar[2].rangeVar.RelName
			c.Columns = yyDollar[3].strs
			yyVAL.node = c
		}
	case 103:
		yyDollar = yyS[yypt-7 : yypt+1]
//line internal/parser/sql.y:403
		{
			c := yyDollar[7].copyStmt
			c.Query = yyDollar[3].node
			yyVAL.node = c
		}
	case 104:
		yyDollar = yyS[yypt-0 : yypt+1]
//line internal/parser/sql.y:406
		{
			yyVAL.strs = nil
		}
	case 105:
		yyDollar = yyS[yypt-3 : yypt+1]
//line internal/parser/sql.y:408
		{
			yyVAL.strs = yyDollar[2].strs
		}
	case 106:
		yyDollar = yyS[yypt-0 : yypt+1]
//line internal/parser/sql.y:411
		{
			yyVAL.copyStmt = &ast.CopyStmt{Format: "text"}
		}
	case 107:
		yyDollar = yyS[yypt-4 : yypt+1]
//line internal/parser/sql.y:413
		{
			c := yyDollar[3].copyStmt
			if c.Format == "" {
				c.Format = "text"
			}
			yyVAL.copyStmt = c
		}
	case 108:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internal/parser/sql.y:417
		{
			yyVAL.copyStmt = yyDollar[1].copyStmt
		}
	case 109:
		yyDollar = yyS[yypt-3 : yypt+1]
//line internal/parser/sql.y:419
		{
			if yyDollar[3].copyStmt.Format != "" {
				yyDollar[1].copyStmt.Format = yyDollar[3].copyStmt.Format
			}
			if yyDollar[3].copyStmt.Delimiter != "" {
				yyDollar[1].copyStmt.Delimiter = yyDollar[3].copyStmt.Delimiter
			}
			if yyDollar[3].copyStmt.Header {
				yyDollar[1].copyStmt.Header = true
			}
			yyVAL.copyStmt = yyDollar[1].copyStmt
		}
	case 110:
		yyDollar = yyS[yypt-2 : yypt+1]
//line internal/parser/sql.y:428
		{
			yyVAL.copyStmt = &ast.CopyStmt{Format: yyDollar[2].str}
		}
	case 111:
		yyDollar = yyS[yypt-2 : yypt+1]
//line internal/parser/sql.y:430
		{
			yyVAL.copyStmt = &ast.CopyStmt{Delimiter: yyDollar[2].str}
		}
	case 112:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internal/parser/sql.y:432
		{
			yyVAL.copyStmt = &ast.CopyStmt{Header: true}
		}
	case 113:
		yyDollar = yyS[yypt-2 : yypt+1]
//line internal/parser/sql.y:436
		{
			yyVAL.node = &ast.TruncateStmt{Table: yyDollar[2].rangeVar.RelName}
		}
	case 114:
		yyDollar = yyS[yypt-3 : yypt+1]
//line internal/parser/sql.y:438
		{
			yyVAL.node = &ast.TruncateStmt{Table: yyDollar[3].rangeVar.RelName}
		}
	case 115:
		yyDollar = yyS[yypt-6 : yypt+1]
//line internal/parser/sql.y:442
		{
			yyVAL.node = &ast.AlterTableStmt{Table: yyDollar[3].rangeVar.RelName, Kind: ast.AlterAddColumn, Column: yyDollar[6].colDef}
		}
	case 116:
		yyDollar = yyS[yypt-5 : yypt+1]
//line internal/parser/sql.y:444
		{
			yyVAL.node = &ast.AlterTableStmt{Table: yyDollar[3].rangeVar.RelName, Kind: ast.AlterAddColumn, Column: yyDollar[5].colDef}
		}
	case 117:
		yyDollar = yyS[yypt-6 : yypt+1]
//line internal/parser/sql.y:446
		{
			yyVAL.node = &ast.AlterTableStmt{Table: yyDollar[3].rangeVar.RelName, Kind: ast.AlterDropColumn, Column: ast.ColumnDef{ColName: yyDollar[6].str}}
		}
	case 118:
		yyDollar = yyS[yypt-5 : yypt+1]
//line internal/parser/sql.y:448
		{
			yyVAL.node = &ast.AlterTableStmt{Table: yyDollar[3].rangeVar.RelName, Kind: ast.AlterDropColumn, Column: ast.ColumnDef{ColName: yyDollar[5].str}}
		}
	case 119:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internal/parser/sql.y:452
		{
			yyVAL.colDefs = []ast.ColumnDef{yyDollar[1].colDef}
		}
	case 120:
		yyDollar = yyS[yypt-3 : yypt+1]
//line internal/parser/sql.y:454
		{
			yyVAL.colDefs = append(yyDollar[1].colDefs, yyDollar[3].colDef)
		}
	case 121:
		yyDollar = yyS[yypt-3 : yypt+1]
//line internal/parser/sql.y:458
		{
			yyVAL.colDef = ast.NewColumnDef(yyDollar[1].str, yyDollar[2].str, yyDollar[3].colQuals)
		}
	case 122:
		yyDollar = yyS[yypt-0 : yypt+1]
//line internal/parser/sql.y:461
		{
			yyVAL.colQuals = nil
		}
	case 123:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internal/parser/sql.y:463
		{
			yyVAL.colQuals = yyDollar[1].colQuals
		}
	case 124:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internal/parser/sql.y:467
		{
			yyVAL.colQuals = []ast.ColQual{yyDollar[1].colQual}
		}
	case 125:
		yyDollar = yyS[yypt-2 : yypt+1]
//line internal/parser/sql.y:469
		{
			yyVAL.colQuals = append(yyDollar[1].colQuals, yyDollar[2].colQual)
		}
	case 126:
		yyDollar = yyS[yypt-2 : yypt+1]
//line internal/parser/sql.y:473
		{
			yyVAL.colQual = ast.ColQual{Kind: ast.ColQualNotNull}
		}
	case 127:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internal/parser/sql.y:475
		{
			yyVAL.colQual = ast.ColQual{Kind: ast.ColQualNull}
		}
	case 128:
		yyDollar = yyS[yypt-2 : yypt+1]
//line internal/parser/sql.y:477
		{
			yyVAL.colQual = ast.ColQual{Kind: ast.ColQualPrimaryKey}
		}
	case 129:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internal/parser/sql.y:479
		{
			yyVAL.colQual = ast.ColQual{Kind: ast.ColQualUnique}
		}
	case 130:
		yyDollar = yyS[yypt-2 : yypt+1]
//line internal/parser/sql.y:481
		{
			yyVAL.colQual = ast.ColQual{Kind: ast.ColQualDefault, Expr: yyDollar[2].node}
		}
	case 131:
		yyDollar = yyS[yypt-2 : yypt+1]
//line internal/parser/sql.y:483
		{
			yyVAL.colQual = ast.ColQual{Kind: ast.ColQualReferences, RefTable: yyDollar[2].rangeVar.RelName}
		}
	case 132:
		yyDollar = yyS[yypt-5 : yypt+1]
//line internal/parser/sql.y:485
		{
			yyVAL.colQual = ast.ColQual{Kind: ast.ColQualReferences, RefTable: yyDollar[2].rangeVar.RelName, RefCol: yyDollar[4].str}
		}
	case 133:
		yyDollar = yyS[yypt-4 : yypt+1]
//line internal/parser/sql.y:487
		{
			yyVAL.colQual = ast.ColQual{Kind: ast.ColQualCheck, Expr: yyDollar[3].node}
		}
	case 134:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internal/parser/sql.y:495
		{
			yyVAL.str = yyDollar[1].str
		}
	case 135:
		yyDollar = yyS[yypt-4 : yypt+1]
//line internal/parser/sql.y:497
		{
			yyVAL.str = yyDollar[1].str
		}
	case 136:
		yyDollar = yyS[yypt-6 : yypt+1]
//line internal/parser/sql.y:499
		{
			yyVAL.str = yyDollar[1].str
		}
	case 137:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internal/parser/sql.y:503
		{
			yyVAL.str = yyDollar[1].str
		}
	case 138:
		yyDollar = yyS[yypt-2 : yypt+1]
//line internal/parser/sql.y:505
		{
			yyVAL.str = yyDollar[1].str + " " + yyDollar[2].str
		}
	case 139:
		yyDollar = yyS[yypt-2 : yypt+1]
//line internal/parser/sql.y:507
		{
			yyVAL.str = yyDollar[1].str + " with"
		}
	case 140:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internal/parser/sql.y:514
		{
			yyVAL.str = yyDollar[1].str
		}
	case 141:
		yyDollar = yyS[yypt-4 : yypt+1]
//line internal/parser/sql.y:516
		{
			yyVAL.str = yyDollar[1].str
		}
	case 142:
		yyDollar = yyS[yypt-6 : yypt+1]
//line internal/parser/sql.y:518
		{
			yyVAL.str = yyDollar[1].str
		}
	case 143:
		yyDollar = yyS[yypt-3 : yypt+1]
//line internal/parser/sql.y:523
		{
			yyVAL.node = &ast.CreateBranchStmt{BranchName: yyDollar[3].str, FromBranch: "main"}
		}
	case 144:
		yyDollar = yyS[yypt-5 : yypt+1]
//line internal/parser/sql.y:525
		{
			yyVAL.node = &ast.CreateBranchStmt{BranchName: yyDollar[3].str, FromBranch: yyDollar[5].str}
		}
	case 145:
		yyDollar = yyS[yypt-5 : yypt+1]
//line internal/parser/sql.y:529
		{
			yyVAL.node = &ast.MergeBranchStmt{SourceBranch: yyDollar[3].str, TargetBranch: yyDollar[5].str}
		}
	case 146:
		yyDollar = yyS[yypt-3 : yypt+1]
//line internal/parser/sql.y:531
		{
			yyVAL.node = &ast.MergeBranchStmt{SourceBranch: yyDollar[3].str, TargetBranch: "main"}
		}
	case 147:
		yyDollar = yyS[yypt-3 : yypt+1]
//line internal/parser/sql.y:535
		{
			yyVAL.node = &ast.DropBranchStmt{BranchName: yyDollar[3].str}
		}
	case 148:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internal/parser/sql.y:540
		{
			yyVAL.nodes = []ast.Node{yyDollar[1].node}
		}
	case 149:
		yyDollar = yyS[yypt-3 : yypt+1]
//line internal/parser/sql.y:542
		{
			yyVAL.nodes = append(yyDollar[1].nodes, yyDollar[3].node)
		}
	case 150:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internal/parser/sql.y:546
		{
			yyVAL.node = &ast.A_Const{Type: ast.ConstInt, Val: yyDollar[1].str}
		}
	case 151:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internal/parser/sql.y:548
		{
			yyVAL.node = &ast.A_Const{Type: ast.ConstFloat, Val: yyDollar[1].str}
		}
	case 152:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internal/parser/sql.y:550
		{
			yyVAL.node = &ast.A_Const{Type: ast.ConstString, Val: yyDollar[1].str}
		}
	case 153:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internal/parser/sql.y:552
		{
			yyVAL.node = &ast.A_Const{Type: ast.ConstBool, Val: "true"}
		}
	case 154:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internal/parser/sql.y:554
		{
			yyVAL.node = &ast.A_Const{Type: ast.ConstBool, Val: "false"}
		}
	case 155:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internal/parser/sql.y:556
		{
			yyVAL.node = &ast.A_Const{Type: ast.ConstNull}
		}
	case 156:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internal/parser/sql.y:558
		{
			yyVAL.node = &ast.ParamRef{Number: yyDollar[1].ival}
		}
	case 157:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internal/parser/sql.y:560
		{
			yyVAL.node = colRefFromRangeVar(yyDollar[1].rangeVar)
		}
	case 158:
		yyDollar = yyS[yypt-3 : yypt+1]
//line internal/parser/sql.y:562
		{
			yyVAL.node = &ast.FuncCall{FuncName: []string{yyDollar[1].str}}
		}
	case 159:
		yyDollar = yyS[yypt-4 : yypt+1]
//line internal/parser/sql.y:564
		{
			yyVAL.node = &ast.FuncCall{FuncName: []string{yyDollar[1].str}, AggStar: true}
		}
	case 160:
		yyDollar = yyS[yypt-4 : yypt+1]
//line internal/parser/sql.y:566
		{
			yyVAL.node = &ast.FuncCall{FuncName: []string{yyDollar[1].str}, Args: yyDollar[3].nodes}
		}
	case 161:
		yyDollar = yyS[yypt-7 : yypt+1]
//line internal/parser/sql.y:568
		{
			yyVAL.node = &ast.FuncCall{FuncName: []string{yyDollar[1].str}, Over: yyDollar[6].windowDef}
		}
	case 162:
		yyDollar = yyS[yypt-8 : yypt+1]
//line internal/parser/sql.y:570
		{
			yyVAL.node = &ast.FuncCall{FuncName: []string{yyDollar[1].str}, AggStar: true, Over: yyDollar[7].windowDef}
		}
	case 163:
		yyDollar = yyS[yypt-8 : yypt+1]
//line internal/parser/sql.y:572
		{
			yyVAL.node = &ast.FuncCall{FuncName: []string{yyDollar[1].str}, Args: yyDollar[3].nodes, Over: yyDollar[7].windowDef}
		}
	case 164:
		yyDollar = yyS[yypt-3 : yypt+1]
//line internal/parser/sql.y:574
		{
			yyVAL.node = yyDollar[2].node
		}
	case 165:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internal/parser/sql.y:576
		{
			yyVAL.node = yyDollar[1].node
		}
	case 166:
		yyDollar = yyS[yypt-3 : yypt+1]
//line internal/parser/sql.y:578
		{
			yyVAL.node = &ast.SubLink{SubSelect: yyDollar[2].node}
		}
	case 167:
		yyDollar = yyS[yypt-5 : yypt+1]
//line internal/parser/sql.y:580
		{
			yyVAL.node = &ast.A_Expr{Kind: ast.AEXPR_IN, Lexpr: yyDollar[1].node, Rexpr: &ast.SubLink{SubSelect: yyDollar[4].node}}
		}
	case 168:
		yyDollar = yyS[yypt-5 : yypt+1]
//line internal/parser/sql.y:582
		{
			yyVAL.node = &ast.A_Expr{Kind: ast.AEXPR_IN, Lexpr: yyDollar[1].node, Rexpr: &ast.List{Items: yyDollar[4].nodes}}
		}
	case 169:
		yyDollar = yyS[yypt-6 : yypt+1]
//line internal/parser/sql.y:584
		{
			yyVAL.node = &ast.BoolExpr{Op: ast.NOT_EXPR, Args: []ast.Node{&ast.A_Expr{Kind: ast.AEXPR_IN, Lexpr: yyDollar[1].node, Rexpr: &ast.SubLink{SubSelect: yyDollar[5].node}}}}
		}
	case 170:
		yyDollar = yyS[yypt-6 : yypt+1]
//line internal/parser/sql.y:586
		{
			yyVAL.node = &ast.BoolExpr{Op: ast.NOT_EXPR, Args: []ast.Node{&ast.A_Expr{Kind: ast.AEXPR_IN, Lexpr: yyDollar[1].node, Rexpr: &ast.List{Items: yyDollar[5].nodes}}}}
		}
	case 171:
		yyDollar = yyS[yypt-3 : yypt+1]
//line internal/parser/sql.y:588
		{
			yyVAL.node = &ast.A_Expr{Kind: ast.AEXPR_OP, Name: yyDollar[2].str, Lexpr: yyDollar[1].node, Rexpr: yyDollar[3].node}
		}
	case 172:
		yyDollar = yyS[yypt-3 : yypt+1]
//line internal/parser/sql.y:590
		{
			yyVAL.node = &ast.A_Expr{Kind: ast.AEXPR_OP, Name: yyDollar[2].str, Lexpr: yyDollar[1].node, Rexpr: yyDollar[3].node}
		}
	case 173:
		yyDollar = yyS[yypt-3 : yypt+1]
//line internal/parser/sql.y:592
		{
			yyVAL.node = &ast.A_Expr{Kind: ast.AEXPR_OP, Name: yyDollar[2].str, Lexpr: yyDollar[1].node, Rexpr: yyDollar[3].node}
		}
	case 174:
		yyDollar = yyS[yypt-3 : yypt+1]
//line internal/parser/sql.y:594
		{
			yyVAL.node = &ast.A_Expr{Kind: ast.AEXPR_OP, Name: "*", Lexpr: yyDollar[1].node, Rexpr: yyDollar[3].node}
		}
	case 175:
		yyDollar = yyS[yypt-3 : yypt+1]
//line internal/parser/sql.y:596
		{
			yyVAL.node = &ast.A_Expr{Kind: ast.AEXPR_OP, Name: yyDollar[2].str, Lexpr: yyDollar[1].node, Rexpr: yyDollar[3].node}
		}
	case 176:
		yyDollar = yyS[yypt-3 : yypt+1]
//line internal/parser/sql.y:598
		{
			yyVAL.node = &ast.A_Expr{Kind: ast.AEXPR_OP, Name: yyDollar[2].str, Lexpr: yyDollar[1].node, Rexpr: yyDollar[3].node}
		}
	case 177:
		yyDollar = yyS[yypt-3 : yypt+1]
//line internal/parser/sql.y:600
		{
			yyVAL.node = &ast.BoolExpr{Op: ast.AND_EXPR, Args: []ast.Node{yyDollar[1].node, yyDollar[3].node}}
		}
	case 178:
		yyDollar = yyS[yypt-3 : yypt+1]
//line internal/parser/sql.y:602
		{
			yyVAL.node = &ast.BoolExpr{Op: ast.OR_EXPR, Args: []ast.Node{yyDollar[1].node, yyDollar[3].node}}
		}
	case 179:
		yyDollar = yyS[yypt-2 : yypt+1]
//line internal/parser/sql.y:604
		{
			yyVAL.node = &ast.BoolExpr{Op: ast.NOT_EXPR, Args: []ast.Node{yyDollar[2].node}}
		}
	case 180:
		yyDollar = yyS[yypt-3 : yypt+1]
//line internal/parser/sql.y:606
		{
			yyVAL.node = &ast.NullTest{Arg: yyDollar[1].node, TestNull: true}
		}
	case 181:
		yyDollar = yyS[yypt-4 : yypt+1]
//line internal/parser/sql.y:608
		{
			yyVAL.node = &ast.NullTest{Arg: yyDollar[1].node, TestNull: false}
		}
	case 182:
		yyDollar = yyS[yypt-3 : yypt+1]
//line internal/parser/sql.y:610
		{
			yyVAL.node = &ast.TypeCast{Arg: yyDollar[1].node, TypeName: yyDollar[3].str}
		}
	case 183:
		yyDollar = yyS[yypt-2 : yypt+1]
//line internal/parser/sql.y:612
		{
			yyVAL.node = &ast.A_Expr{Kind: ast.AEXPR_OP, Name: yyDollar[1].str, Rexpr: yyDollar[2].node}
		}
	case 184:
		yyDollar = yyS[yypt-5 : yypt+1]
//line internal/parser/sql.y:618
		{
			yyVAL.node = &ast.CaseExpr{Arg: yyDollar[2].node, Whens: yyDollar[3].caseWhens, Else: yyDollar[4].node}
		}
	case 185:
		yyDollar = yyS[yypt-0 : yypt+1]
//line internal/parser/sql.y:621
		{
			yyVAL.node = nil
		}
	case 186:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internal/parser/sql.y:623
		{
			yyVAL.node = yyDollar[1].node
		}
	case 187:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internal/parser/sql.y:627
		{
			yyVAL.caseWhens = []*ast.CaseWhen{yyDollar[1].caseWhen}
		}
	case 188:
		yyDollar = yyS[yypt-2 : yypt+1]
//line internal/parser/sql.y:629
		{
			yyVAL.caseWhens = append(yyDollar[1].caseWhens, yyDollar[2].caseWhen)
		}
	case 189:
		yyDollar = yyS[yypt-4 : yypt+1]
//line internal/parser/sql.y:633
		{
			yyVAL.caseWhen = &ast.CaseWhen{Cond: yyDollar[2].node, Result: yyDollar[4].node}
		}
	case 190:
		yyDollar = yyS[yypt-0 : yypt+1]
//line internal/parser/sql.y:636
		{
			yyVAL.node = nil
		}
	case 191:
		yyDollar = yyS[yypt-2 : yypt+1]
//line internal/parser/sql.y:638
		{
			yyVAL.node = yyDollar[2].node
		}
	case 192:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internal/parser/sql.y:642
		{
			yyVAL.rangeVar = &ast.RangeVar{RelName: yyDollar[1].str}
		}
	case 193:
		yyDollar = yyS[yypt-3 : yypt+1]
//line internal/parser/sql.y:644
		{
			yyVAL.rangeVar = &ast.RangeVar{SchemaName: yyDollar[1].str, RelName: yyDollar[3].str}
		}
	case 194:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internal/parser/sql.y:648
		{
			yyVAL.strs = []string{yyDollar[1].str}
		}
	case 195:
		yyDollar = yyS[yypt-3 : yypt+1]
//line internal/parser/sql.y:650
		{
			yyVAL.strs = append(yyDollar[1].strs, yyDollar[3].str)
		}
	}
	goto yystack /* stack new state and value */
}
